In [ ]:

import numpy as np


#### 미니 실습 — 먼저 설계하고 답안은 나중에 공개

#1. 4부터 16까지 3씩 증가하는 배열을 만듭니다.
#2. 3행 2열의 정수 0 배열을 만듭니다.

data = np.arange(4, 17, 3)
print(f"data: {data}, shape: {data.shape}, ndim: {data.ndim}, size: {data.size}, dtype: {data.dtype}")

result = np.zeros((3, 2), dtype=int)
print(f"result: {result}, shape: {result.shape}, ndim: {result.ndim}, size: {result.size}, dtype: {result.dtype}")

result1 = np.zeros((3, 2, 2), dtype=int)
print(f"result1: {result1}, shape: {result1.shape}, ndim: {result1.ndim}, size: {result1.size}, dtype: {result1.dtype}")




data: [ 4  7 10 13 16], shape: (5,), ndim: 1, size: 5, dtype: int64
result: [[0 0]
 [0 0]
 [0 0]], shape: (3, 2), ndim: 2, size: 6, dtype: int64
result1: [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]], shape: (3, 2, 2), ndim: 3, size: 12, dtype: int64


In [18]:
#2차원 데이터 슬라이싱
regions = np.array(["서울", "부산", "대전"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4"])
sales = np.array([
    [10, 12, 14, 16],
    [20, 18, 21, 25],
    [11, 13, 15, 17],
])

print("지역:", regions)
print("분기:", quarters)
print("매출표:\n", sales)
print("shape:", sales.shape)

print("부산·대전의 Q2~Q4:\n", sales[1:3, 1:4])
print("모든 지역의 Q2~Q3:\n", sales[:, 1:3])
print("서울 지역의 Q2~Q3:\n", sales[0:1, 1:3] )
print("서울 지역의 Q2~Q4:\n", sales[0:1, 1:4] )
print("서울 지역의 Q1~Q4:\n", sales[0:1, :4] )

sales[0:1]

지역: ['서울' '부산' '대전']
분기: ['Q1' 'Q2' 'Q3' 'Q4']
매출표:
 [[10 12 14 16]
 [20 18 21 25]
 [11 13 15 17]]
shape: (3, 4)
부산·대전의 Q2~Q4:
 [[18 21 25]
 [13 15 17]]
모든 지역의 Q2~Q3:
 [[12 14]
 [18 21]
 [13 15]]
서울 지역의 Q2~Q3:
 [[12 14]]
서울 지역의 Q2~Q4:
 [[12 14 16]]
서울 지역의 Q1~Q4:
 [[10 12 14 16]]


array([[10, 12, 14, 16]])

In [ ]:
#1. 마스킹작업
years = np.arange(2010, 2020)
gdp = np.array([6610, 7637, 8127, 8885, 10385,
                12565, 14403, 12398, 8282, 10672])

mask = gdp > 10000
over_10000 = gdp > 10000

print("GDP:", gdp)
print("조건:", over_10000)
print("~조건(not):", ~over_10000)
print("조건 dtype:", over_10000.dtype)
print("같은 shape:", gdp.shape == over_10000.shape) ##항상 점검


mask_result = gdp[over_10000]
print(f'mask_result: {mask_result}')
print(f'mask_result revers: {~mask_result}')

print(\n)
##################################### 중요 : 컬럼 위치 전제 
mask = gdp > 10000
selected_years = years[mask] #--> selected_gdp 와 컬럼 위치가 같다는 전제 (True, False, ...)
selected_gdp = gdp[mask]
print("선택된 연도:", selected_years)
print("선택된 GDP :", selected_gdp)
print("모두 조건 만족?", np.all(selected_gdp > 10000))




GDP: [ 6610  7637  8127  8885 10385 12565 14403 12398  8282 10672]
조건: [False False False False  True  True  True  True False  True]
~조건(not): [ True  True  True  True False False False False  True False]
조건 dtype: bool
같은 shape: True
mask_result: [10385 12565 14403 12398 10672]
mask_result revers: [-10386 -12566 -14404 -12399 -10673]

선택된 연도: [2014 2015 2016 2017 2019]
선택된 GDP : [10385 12565 14403 12398 10672]
모두 조건 만족? True


In [ ]:
문제: 1부터 100까지의 정수에서 짝수만 선택합니다.

설계 질문:

1. 1부터 100까지 만들 `arange`의 stop은?
2. 짝수는 2로 나눈 나머지가 무엇인가?
3. 조건 결과를 배열 대괄호 어디에 넣는가?

In [37]:
#풀이

arr1 = np.arange(1, 101)
print(f'arr1: {arr1}')

mask1 = arr1 % 2 == 0
print(f'mask: {mask}')

arr2 = arr1[mask1]
print(f'arr2: {arr2}')

arr3 = arr2 * 2
print(f'arr3: {arr3}')


arr1: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
mask: [False False False False  True  True  True  True False  True]
arr2: [  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
arr3: [  4   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68  72
  76  80  84  88  92  96 100 104 108 112 116 120 124 128 132 136 140 144
 148 152 156 160 164 168 172 176 180 184 188 192 196 200]
