---

## Part 0. 리스트와 배열은 무엇이 다른가

카페 체인 '위어드커피'의 운영 데이터를 가지고 NumPy를 연습합니다.

이 문제지는 강의 노트북과 **같은 순서, 다른 데이터**로 만들어졌습니다.
강의에서 쓴 쇼핑몰 매출·GDP·지역 분기 매출 대신, 여기서는 카페의 메뉴·방문자·지점 데이터를 씁니다.

**푸는 순서는 반드시 이 순서를 지킵니다.**

1. 문제를 읽는다 (아직 키보드를 만지지 않는다)
2. `[한글 설계]`를 한국어 문장으로 먼저 적는다
3. 그 한국어 문장을 파이썬 한 줄씩으로 옮긴다
4. 실행하고 **기대 출력**과 비교한다
5. 다르면 한 번에 한 곳만 고치고 다시 실행한다

### 문제 01. 리스트에 2를 곱하면 무슨 일이 벌어지는가

카페 메뉴 3개의 가격이 있습니다: 아메리카노 4500원, 라떼 5000원, 콜드브루 5500원.

'모든 가격을 2배로 올린 가격표'를 만들고 싶습니다.

파이썬 리스트에 `* 2`를 하면 우리가 원하는 결과가 나올까요?
리스트와 NumPy 배열에 각각 `* 2`를 해 보고, **결과와 길이**를 비교하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 리스트에 2를 곱한 결과와 그 길이를 출력한다
2. 같은 값을 NumPy 배열로 만든다
3. 배열에 2를 곱한 결과와 그 길이를 출력한다
```

In [ ]:
import numpy as np

price_list = [4500, 5000, 5500]

# [옮기기] 리스트에 2를 곱한 결과를 본다
print("리스트 * 2      :", price_list * 2)
print("리스트 * 2 길이 :", len(price_list * 2))

# [옮기기] 같은 값을 NumPy 배열로 만든다
price_array = np.array(price_list)

# [옮기기] 배열에 2를 곱한 결과를 본다
print("배열 * 2        :", price_array * 2)
print("배열 * 2 길이   :", len(price_array * 2))

리스트 * 2      : [4500, 5000, 5500, 4500, 5000, 5500]
리스트 * 2 길이 : 6
배열 * 2        : [ 9000 10000 11000]
배열 * 2 길이   : 3


**해설**

- 리스트의 `* 2`는 **이어 붙이기(반복)** 입니다. 값이 3개에서 6개로 늘어납니다.
- 배열의 `* 2`는 **모든 원소에 곱하기**입니다. 값의 개수는 3개 그대로입니다.
- 우리가 원한 '가격 2배'는 배열 쪽 동작입니다.

리스트가 틀린 것이 아니라, **계산 목적에는 배열이 맞는 도구**입니다.

### 문제 02. ndim, shape, size 읽기

같은 카페 데이터를 두 가지 모양으로 준비했습니다.

- `cups` : 메뉴 5개의 하루 판매 잔 수 (1차원)
- `sold` : 지점 3곳 × 시간대 4개의 판매 잔 수 (2차원)

두 배열의 `ndim`, `shape`, `size`를 각각 출력하세요.
그리고 `shape`와 `size`가 어떻게 다른지 한 문장으로 설명하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 두 배열을 (이름, 배열) 짝으로 묶는다
2. 반복문으로 하나씩 꺼낸다
3. 각각 ndim, shape, size를 출력한다
```

In [ ]:
import numpy as np

cups = np.array([320, 180, 145, 60, 95])

sold = np.array([
    [42,  88, 61, 25],
    [30,  75, 94, 48],
    [55, 102, 47, 12],
])

# [옮기기] (이름, 배열) 짝을 만들어 하나씩 꺼낸다
for label, array in [("cups", cups), ("sold", sold)]:
    print(label)
    print("  ndim :", array.ndim)   # 축(차원)이 몇 개인가
    print("  shape:", array.shape)  # 각 축의 길이 (행, 열)
    print("  size :", array.size)   # 안에 들어 있는 값의 총 개수

cups
  ndim : 1
  shape: (5,)
  size : 5
sold
  ndim : 2
  shape: (3, 4)
  size : 12


**해설**

- `ndim` : 축이 몇 개인가. 1차원은 1, 표는 2.
- `shape` : 축마다 길이가 얼마인가. `(3, 4)`는 3행 4열.
- `size` : 값이 총 몇 개인가. `(3, 4)`이면 3 × 4 = 12.

`shape`는 **모양**, `size`는 **개수**입니다.
`reshape`가 되는지 안 되는지는 항상 `size`가 결정합니다.

---

## Part 1. 배열은 모양과 데이터 타입을 가진다

배열은 `ndim`(차원 수), `shape`(모양), `size`(값 개수), `dtype`(데이터 종류)를 가집니다.
정확한 비트 수보다 **정수인지 실수인지 문자열인지**를 먼저 봅니다.

### 문제 03. dtype은 하나로 통일된다

아래 세 배열을 만들고 각각의 값과 `dtype`을 출력하세요.

1. `[10, 20, 30]`
2. `[10, 20, 30.5]`
3. `[10, 20, "30"]`

출력 결과를 보고, NumPy가 서로 다른 타입을 만났을 때 **어느 쪽으로 통일하는지** 한 문장으로 적으세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 세 배열을 각각 만든다
2. 값과 dtype을 같이 출력한다
3. 정수 → 실수 → 문자열 중 어느 방향으로 통일되는지 본다
```

In [ ]:
import numpy as np

# [옮기기] 정수만 있는 배열
ints = np.array([10, 20, 30])

# [옮기기] 정수와 실수가 섞인 배열
mixed_number = np.array([10, 20, 30.5])

# [옮기기] 숫자와 문자열이 섞인 배열
mixed_text = np.array([10, 20, "30"])

print(ints, "->", ints.dtype)
print(mixed_number, "->", mixed_number.dtype)
print(mixed_text, "->", mixed_text.dtype)

[10 20 30] -> int64
[10.  20.  30.5] -> float64
['10' '20' '30'] -> <U21


**해설**

NumPy 배열은 보통 **하나의 dtype**만 가집니다. 섞이면 '더 넓게 담을 수 있는 쪽'으로 끌려갑니다.

```text
정수  ->  실수  ->  문자열
(좁다)            (넓다)
```

- 정수 + 실수 → 전부 실수 (`10` 이 `10.` 으로 보임)
- 숫자 + 문자열 → 전부 문자열 (`<U...` 는 유니코드 문자열이라는 뜻)

문자열이 되어 버리면 `sum()` 같은 계산이 막힙니다.
그래서 데이터를 만들 때 **의도한 dtype이 맞는지**를 먼저 확인합니다.

### 문제 04. astype으로 타입 바꾸기 (버림에 주의)

매장 4곳의 실내 온도가 실수로 기록되어 있습니다.

```python
temps = np.array([21.7, 24.3, 19.8, 26.5])
```

이 값을 정수형으로 바꾼 배열을 만들고, 변환 전/후의 값과 dtype을 출력하세요.
그리고 **원본 `temps`가 그대로 남아 있는지**도 함께 출력해 확인하세요.

변환 결과를 보고 '반올림인지 버림인지' 판단해 적으세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. temps 배열을 만든다
2. astype(int)로 정수형 배열을 새로 만든다
3. 변환 전 값·dtype, 변환 후 값·dtype, 원본을 모두 출력한다
```

In [ ]:
import numpy as np

temps = np.array([21.7, 24.3, 19.8, 26.5])

# [옮기기] 정수형으로 바꾼 '새 배열'을 만든다 (원본은 바뀌지 않는다)
temps_int = temps.astype(int)

print("변환 전:", temps, temps.dtype)
print("변환 후:", temps_int, temps_int.dtype)
print("원본 유지:", temps)

변환 전: [21.7 24.3 19.8 26.5] float64
변환 후: [21 24 19 26] int64
원본 유지: [21.7 24.3 19.8 26.5]


In [ ]:
assert temps_int.tolist() == [21, 24, 19, 26]
assert temps.dtype == np.float64
print("검증 통과: astype은 버림이고, 원본은 유지됩니다.")

검증 통과: astype은 버림이고, 원본은 유지됩니다.


**해설**

- `astype`은 **새 배열을 반환**합니다. 원본은 그대로 남습니다.
- `21.7 → 21`, `26.5 → 26`. 반올림이 아니라 **소수점 버림**입니다.
- 반올림이 필요하면 `np.round(temps).astype(int)` 처럼 두 단계로 씁니다.

데이터 분석에서 '왜 값이 1 작지?' 하는 사고는 대부분 여기서 시작합니다.

---

## Part 2. NumPy가 배열을 대신 만들어 준다

`np.arange(start, stop, step)` / `np.zeros(shape)` / `np.ones(shape)`

반복 앵커: **시작은 포함, 끝은 제외**

### 문제 05. arange로 규칙적인 수열 만들기

`np.arange`로 다음 세 배열을 만들고, 각각 값과 `size`를 출력하세요.

1. 0부터 9까지 (10개)
2. 6부터 20까지 (1씩 증가)
3. 5부터 50까지 5씩 증가

**핵심 앵커: 시작은 포함, 끝은 제외.** stop에 무엇을 넣어야 하는지 먼저 종이에 적으세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 0부터 9까지이므로 stop은 10이다
2. 6부터 20까지이므로 stop은 21이다
3. 5부터 50까지 5씩이므로 start=5, stop=51, step=5이다
```

In [ ]:
import numpy as np

# [옮기기] 0부터 9까지 -> stop은 포함되지 않으므로 10
seq_a = np.arange(10)

# [옮기기] 6부터 20까지 -> 20을 포함하려면 stop은 21
seq_b = np.arange(6, 21)

# [옮기기] 5부터 50까지 5씩 -> 50을 포함하려면 stop은 51
seq_c = np.arange(5, 51, 5)

print("seq_a:", seq_a, "| size =", seq_a.size)
print("seq_b:", seq_b, "| size =", seq_b.size)
print("seq_c:", seq_c, "| size =", seq_c.size)

seq_a: [0 1 2 3 4 5 6 7 8 9] | size = 10
seq_b: [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] | size = 15
seq_c: [ 5 10 15 20 25 30 35 40 45 50] | size = 10


In [ ]:
assert seq_a.size == 10 and seq_a[-1] == 9
assert seq_b.size == 15 and seq_b[-1] == 20
assert seq_c.size == 10 and seq_c[-1] == 50
print("검증 통과: 세 배열 모두 끝 값이 의도대로 포함되었습니다.")

검증 통과: 세 배열 모두 끝 값이 의도대로 포함되었습니다.


**해설**

`np.arange(start, stop, step)`에서 **stop은 절대 포함되지 않습니다.**

- `20까지` 원하면 stop은 `21`
- `50까지 5씩` 원하면 stop은 `51`

`stop`을 `20`으로 쓰면 19에서 끊깁니다. 초보 단계에서 가장 자주 나오는 어긋남입니다.
값을 세지 말고 `size`를 출력해서 확인하는 습관을 들이세요.

### 문제 06. zeros와 ones로 빈 표 만들기

4주 동안 3개 지점의 예약 건수를 기록할 **빈 표**를 미리 만들어 두려고 합니다.

1. 4행 3열, 값이 전부 정수 `0`인 표를 만드세요.
2. 2행 5열, 값이 전부 `1.0`인 표를 만드세요.
3. 두 표의 `shape`와 `dtype`을 출력하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 4주 × 3지점이므로 shape는 (4, 3)이다
2. 정수 0을 원하므로 dtype=int을 준다
3. 1로 채운 표는 ones((2, 5))로 만든다
```

In [ ]:
import numpy as np

# [옮기기] 4주(행) × 3지점(열) 짜리 정수 0 표
booking_table = np.zeros((4, 3), dtype=int)

# [옮기기] 2행 5열 짜리 1.0 표 (dtype을 주지 않으면 기본이 실수)
one_table = np.ones((2, 5))

print("예약 초기표:\n", booking_table)
print("1로 채운 표:\n", one_table)
print("shape:", booking_table.shape, one_table.shape)
print("dtype:", booking_table.dtype, one_table.dtype)

예약 초기표:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
1로 채운 표:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
shape: (4, 3) (2, 5)
dtype: int64 float64


In [ ]:
assert booking_table.shape == (4, 3)
assert booking_table.sum() == 0
assert one_table.shape == (2, 5)
print("검증 통과: 빈 표의 모양과 값이 의도대로입니다.")

검증 통과: 빈 표의 모양과 값이 의도대로입니다.


**해설**

- `np.zeros`와 `np.ones`는 **shape를 괄호로 묶어 하나의 값처럼** 넘깁니다: `np.zeros((4, 3))`
- 괄호를 하나만 쓰면 `np.zeros(4, 3)` 처럼 되어 오류가 납니다.
- 기본 dtype은 실수(`float64`)입니다. 정수 표가 필요하면 `dtype=int`을 직접 줍니다.

'결과를 담을 빈 그릇을 먼저 만들어 두고 채워 넣는' 방식은 실무에서 매우 자주 씁니다.

---

## Part 3. 배열의 모양 바꾸기

`reshape`는 값의 순서를 유지하면서 모양만 바꿉니다.

반복 질문: **숫자가 총 몇 개인가?**

### 문제 07. reshape로 같은 값의 모양만 바꾸기

`np.arange(12)`로 값 12개를 만든 뒤, 다음 세 가지 모양으로 각각 바꾸세요.

1. 3행 4열
2. 4행 3열
3. 2행 6열

각 결과와 `shape`, `size`를 출력하고, **원본 배열이 바뀌지 않았는지**도 확인하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. np.arange(12)로 값 12개를 만든다
2. reshape(3, 4) / reshape(4, 3) / reshape(2, 6)을 각각 새 이름에 저장한다
3. 결과와 shape, size, 그리고 원본을 출력한다
```

In [ ]:
import numpy as np

base = np.arange(12)

# [옮기기] 값 12개를 3행 4열로 (12 = 3 × 4)
shape_3x4 = base.reshape(3, 4)

# [옮기기] 값 12개를 4행 3열로 (12 = 4 × 3)
shape_4x3 = base.reshape(4, 3)

# [옮기기] 값 12개를 2행 6열로 (12 = 2 × 6)
shape_2x6 = base.reshape(2, 6)

print("원본:", base, "| shape =", base.shape)
print("3행 4열:\n", shape_3x4)
print("4행 3열:\n", shape_4x3)
print("2행 6열:\n", shape_2x6)
print("size 비교:", base.size, shape_3x4.size, shape_4x3.size, shape_2x6.size)

원본: [ 0  1  2  3  4  5  6  7  8  9 10 11] | shape = (12,)
3행 4열:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4행 3열:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
2행 6열:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
size 비교: 12 12 12 12


**해설**

- `reshape`는 값을 **왼쪽에서 오른쪽, 위에서 아래 순서로** 다시 담습니다. 값의 순서는 유지됩니다.
- 어떤 모양으로 바꾸든 `size`는 항상 12로 같습니다.
- `reshape`도 **새 배열을 돌려주고 원본은 유지**합니다.

`size`가 같은 모양끼리만 갈아탈 수 있다는 점이 다음 문제의 핵심입니다.

### 문제 08. reshape가 실패하는 이유를 직접 확인하고 고치기

값 12개를 `reshape(5, 3)`으로 바꾸려고 하면 어떻게 될까요?

**먼저 예측하세요.** 성공할까요, 실패할까요? 실패한다면 왜일까요?

그다음 `try / except ValueError`로 감싸서 실행하고, 오류의 **종류 이름**과 **이유**를 출력하세요.
마지막으로 값 개수를 바꾸지 않고 성공하는 모양 하나를 골라 다시 실행하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 12개를 (5, 3)에 넣으려면 15칸이 필요하다 -> 칸이 남으므로 실패한다
2. try / except ValueError로 감싸 오류 종류와 이유를 출력한다
3. 값 개수 12를 유지하는 모양(예: 6행 2열)으로 다시 실행한다
```

In [ ]:
import numpy as np

base = np.arange(12)

# [옮기기] 실패가 예상되는 reshape를 try로 감싼다
try:
    impossible = base.reshape(5, 3)
except ValueError as error:
    print("예상한 오류 종류:", type(error).__name__)
    print("이유: 값 12개를", 5 * 3, "칸 모양에 넣을 수 없습니다.")
    print("원본 size:", base.size)

# [옮기기] 값 개수 12를 그대로 유지하는 모양으로 고쳐서 다시 실행한다
retry = base.reshape(6, 2)
print("수정 후:\n", retry)
print("retry shape:", retry.shape, "| size:", retry.size)

예상한 오류 종류: ValueError
이유: 값 12개를 15 칸 모양에 넣을 수 없습니다.
원본 size: 12
수정 후:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
retry shape: (6, 2) | size: 12


**해설**

오류를 분류해 봅니다.

- 문법 오류인가? → 아니오
- 라이브러리 설치 문제인가? → 아니오
- **모양 계약 오류인가? → 예**

`12`는 `5 × 3 = 15`에 들어가지 않습니다. 남거나 모자라면 NumPy는 무조건 거절합니다.

수정 후보는 두 가지뿐입니다.

1. 값 개수 12를 유지하고 `(2,6) (6,2) (3,4) (4,3) (12,1)` 중에서 고른다
2. `(5,3)`을 꼭 쓰고 싶으면 값 개수를 15개로 바꾼다

**한 번에 하나만 바꾸고 다시 실행합니다.** 두 개를 동시에 바꾸면 무엇이 고쳤는지 알 수 없습니다.

### 문제 09. -1을 써서 나머지 축을 자동으로 계산하게 하기

값 24개를 만든 뒤, 다음 두 가지를 `-1`을 사용해서 만드세요.

1. 열이 6개이고 행 개수는 NumPy가 알아서 정하게 하기
2. 행이 4개이고 열 개수는 NumPy가 알아서 정하게 하기

각각의 `shape`를 출력해서 몇 행 몇 열이 되었는지 확인하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. np.arange(24)로 값 24개를 만든다
2. 열이 6개이면 reshape(-1, 6)이다
3. 행이 4개이면 reshape(4, -1)이다
```

In [ ]:
import numpy as np

base24 = np.arange(24)

# [옮기기] 열은 6개로 고정, 행은 NumPy가 계산 (24 ÷ 6 = 4)
auto_rows = base24.reshape(-1, 6)

# [옮기기] 행은 4개로 고정, 열은 NumPy가 계산 (24 ÷ 4 = 6)
auto_cols = base24.reshape(4, -1)

print("reshape(-1, 6) shape ->", auto_rows.shape)
print("reshape(4, -1) shape ->", auto_cols.shape)
print(auto_rows)

reshape(-1, 6) shape -> (4, 6)
reshape(4, -1) shape -> (4, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
assert auto_rows.shape == (4, 6)
assert auto_cols.shape == (4, 6)
print("검증 통과: 두 방법 모두 (4, 6)이 되었습니다.")

검증 통과: 두 방법 모두 (4, 6)이 되었습니다.


**해설**

`-1`은 "이 자리는 네가 계산해라"라는 뜻입니다. 나머지 축이 정해지면 답은 하나로 결정됩니다.

- `24`를 열 6개로 나누면 행은 4개
- `24`를 행 4개로 나누면 열은 6개

주의: `-1`은 **한 자리에만** 쓸 수 있습니다. `reshape(-1, -1)`은 계산이 불가능해서 오류가 납니다.
또한 나누어떨어지지 않으면(`24`를 `5`열로) 역시 오류입니다.

---

## Part 4. 원하는 데이터를 위치로 찾기 (1차원)

- 첫 번째 위치: `0`
- 마지막 위치: `-1`
- 슬라이싱 `a[start:stop]`은 **start 포함, stop 제외**

### 문제 10. 위치 번호로 값 하나 꺼내기

카페의 1월~12월 월별 방문자 수 데이터가 있습니다.

`months`와 `visitors`를 만든 뒤 다음을 출력하세요.

1. 1월 방문자 수
2. 7월 방문자 수
3. 마지막 달(12월) 방문자 수 — **음수 인덱스를 사용**
4. 뒤에서 두 번째 달 방문자 수

`months`와 `visitors`의 길이가 같은지도 먼저 확인하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. months는 1부터 12까지이므로 arange(1, 13)이다
2. 1월은 위치 0, 7월은 위치 6이다 (사람이 세는 수 - 1)
3. 마지막은 -1, 뒤에서 두 번째는 -2이다
```

In [ ]:
import numpy as np

months = np.arange(1, 13)
visitors = np.array([1820, 1650, 2010, 2240, 2380, 2510,
                     2760, 2890, 2430, 2180, 1970, 2300])

# [옮기기] 두 배열의 길이가 같은지 먼저 확인한다
print("월:", months)
print("방문자:", visitors)
print("길이가 같은가?", months.size == visitors.size)

# [옮기기] 1월은 위치 0, 7월은 위치 6
print("1월 방문자      :", visitors[0])
print("7월 방문자      :", visitors[6])

# [옮기기] 마지막은 -1, 뒤에서 두 번째는 -2
print("마지막 달 방문자:", visitors[-1])
print("뒤에서 두 번째  :", visitors[-2])

월: [ 1  2  3  4  5  6  7  8  9 10 11 12]
방문자: [1820 1650 2010 2240 2380 2510 2760 2890 2430 2180 1970 2300]
길이가 같은가? True
1월 방문자      : 1820
7월 방문자      : 2760
마지막 달 방문자: 2300
뒤에서 두 번째  : 1970


**해설**

인덱스는 **값이 아니라 위치 번호**입니다.

```text
사람이 세는 순서 :  1월  2월  3월 ...  11월  12월
파이썬 인덱스    :   0    1    2  ...   10    11
뒤에서 세는 번호 : -12  -11  -10 ...   -2    -1
```

`7월 = 위치 6`. **사람이 세는 수에서 1을 뺀다**가 규칙입니다.

두 배열을 짝지어 쓸 때는 항상 길이가 같은지 먼저 확인합니다.
길이가 다르면 `months[mask]` 같은 코드가 조용히 틀린 답을 낼 수 있습니다.

### 문제 11. 슬라이싱으로 구간 꺼내기

같은 `visitors` 배열에서 다음 네 가지를 출력하세요.

1. 3월부터 5월까지 (사람이 세는 기준)
2. 처음 4개월
3. 9월부터 끝까지
4. 1월부터 두 달 간격으로

각각 코드를 쓰기 전에 `start`와 `stop`을 종이에 먼저 적으세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 3월~5월 -> 시작 위치 2, 끝은 5월 다음인 위치 5 -> [2:5]
2. 처음 4개월 -> [:4]
3. 9월부터 끝까지 -> 9월은 위치 8 -> [8:]
4. 두 달 간격 -> step 2 -> [0::2] 또는 [::2]
```

In [ ]:
import numpy as np

visitors = np.array([1820, 1650, 2010, 2240, 2380, 2510,
                     2760, 2890, 2430, 2180, 1970, 2300])

# [옮기기] 3월(위치 2)부터 5월(위치 4)까지 -> stop은 하나 더 큰 5
print("3~5월    :", visitors[2:5])

# [옮기기] 처음 4개월 -> start를 비우면 0부터
print("처음 4개월:", visitors[:4])

# [옮기기] 9월(위치 8)부터 끝까지 -> stop을 비우면 끝까지
print("9월~12월 :", visitors[8:])

# [옮기기] 처음부터 끝까지 두 칸씩 건너뛰기
print("두 달 간격:", visitors[::2])

3~5월    : [2010 2240 2380]
처음 4개월: [1820 1650 2010 2240]
9월~12월 : [2430 2180 1970 2300]
두 달 간격: [1820 2010 2380 2760 2430 1970]


In [ ]:
assert visitors[2:5].tolist() == [2010, 2240, 2380]
assert visitors[:4].size == 4
assert visitors[8:].size == 4
print("검증 통과: 구간이 의도대로 잘렸습니다.")

검증 통과: 구간이 의도대로 잘렸습니다.


**해설**

슬라이싱의 문장은 `array[start : stop : step]` 입니다.

- **start는 포함, stop은 제외** (arange와 같은 규칙)
- `start`를 비우면 처음부터, `stop`을 비우면 끝까지
- `step`은 몇 칸씩 건너뛸지

`3월부터 5월까지`를 `[2:4]`로 쓰면 5월이 빠집니다.
"사람이 세는 마지막 번호"를 그대로 stop에 쓰는 것이 정답입니다: 5월 → stop = 5.

### 문제 12. copy를 쓰지 않으면 원본이 함께 바뀐다

1월 방문자 수가 잘못 입력되어 `1820`을 `2000`으로 고치려 합니다.

두 가지를 비교해 보세요.

1. `visitors.copy()`로 사본을 만들어 첫 값을 바꾼 뒤, **원본**의 첫 값을 출력
2. 슬라이싱 `visitors[:3]`을 변수에 저장한 뒤 그 첫 값을 바꾸고, **원본**의 첫 값을 출력

두 경우에서 원본이 어떻게 달라지는지 관찰하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. copy()로 사본을 만들고 첫 값을 2000으로 바꾼 뒤 원본을 확인한다
2. 원본을 다시 원래 값으로 되돌린다
3. 슬라이싱 결과를 변수에 담아 첫 값을 바꾼 뒤 원본을 확인한다
```

In [ ]:
import numpy as np

visitors = np.array([1820, 1650, 2010, 2240, 2380, 2510,
                     2760, 2890, 2430, 2180, 1970, 2300])

# [옮기기] 1) copy()로 완전히 독립된 사본을 만든다
safe_edit = visitors.copy()
safe_edit[0] = 2000

print("[copy 사용]")
print("  사본 첫 값 :", safe_edit[0])
print("  원본 첫 값 :", visitors[0], "<- 그대로 유지됨")

# [옮기기] 2) 슬라이싱 결과를 그대로 변수에 담는다 (사본이 아니다)
view_edit = visitors[:3]
view_edit[0] = 2000

print("[슬라이싱 사용]")
print("  잘라낸 것 첫 값:", view_edit[0])
print("  원본 첫 값     :", visitors[0], "<- 같이 바뀜")

[copy 사용]
  사본 첫 값 : 2000
  원본 첫 값 : 1820 <- 그대로 유지됨
[슬라이싱 사용]
  잘라낸 것 첫 값: 2000
  원본 첫 값     : 2000 <- 같이 바뀜


In [ ]:
assert visitors[0] == 2000
print("검증 통과: 슬라이싱은 원본과 연결되어 있습니다.")

검증 통과: 슬라이싱은 원본과 연결되어 있습니다.


**해설**

NumPy의 슬라이싱은 **값을 복사하지 않습니다.** 원본의 일부를 '들여다보는 창(view)'을 돌려줍니다.
창을 통해 값을 바꾸면 원본도 바뀝니다.

- 원본을 지키고 싶다 → `.copy()`
- 메모리를 아끼고 원본과 연결된 채 쓰고 싶다 → 슬라이싱 그대로

파이썬 리스트는 슬라이싱이 복사본이라서 이 부분에서 습관이 어긋납니다.
**NumPy는 다르다**는 것을 여기서 한 번 놀라 두고 가는 것이 목적입니다.

---

## Part 5. 표에서 원하는 값 찾기 (2차원)

2차원 배열의 기본 문장은 `array[행, 열]` 입니다.
콜론 하나 `:`는 그 축을 **전부** 선택합니다.

### 문제 13. 표에서 값 한 칸 꺼내기

지점 3곳 × 시간대 4개의 판매 잔 수 표입니다.

```text
        아침  점심  저녁  야간
강남     42    88    61    25
홍대     30    75    94    48
판교     55   102    47    12
```

다음 값을 출력하세요.

1. 홍대 지점의 저녁 판매량
2. 판교 지점의 점심 판매량
3. 강남 지점의 야간 판매량

각각 `[행, 열]`의 숫자를 먼저 종이에 적고 코드로 옮기세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 행: 강남 0, 홍대 1, 판교 2
2. 열: 아침 0, 점심 1, 저녁 2, 야간 3
3. 홍대 저녁 = [1, 2], 판교 점심 = [2, 1], 강남 야간 = [0, 3]
```

In [ ]:
import numpy as np

branches = np.array(["강남", "홍대", "판교"])
timeslots = np.array(["아침", "점심", "저녁", "야간"])
sold = np.array([
    [42,  88, 61, 25],
    [30,  75, 94, 48],
    [55, 102, 47, 12],
])

print("표:\n", sold)
print("shape:", sold.shape, "(행 = 지점 3, 열 = 시간대 4)")

# [옮기기] 홍대는 행 1, 저녁은 열 2
print("홍대 저녁:", sold[1, 2])

# [옮기기] 판교는 행 2, 점심은 열 1
print("판교 점심:", sold[2, 1])

# [옮기기] 강남은 행 0, 야간은 열 3
print("강남 야간:", sold[0, 3])

표:
 [[ 42  88  61  25]
 [ 30  75  94  48]
 [ 55 102  47  12]]
shape: (3, 4) (행 = 지점 3, 열 = 시간대 4)
홍대 저녁: 94
판교 점심: 102
강남 야간: 25


In [ ]:
assert sold[1, 2] == 94
assert sold[2, 1] == 102
assert sold[0, 3] == 25
print("검증 통과: 행과 열 순서를 지켰습니다.")

검증 통과: 행과 열 순서를 지켰습니다.


**해설**

2차원 배열의 기본 문장은 `array[행, 열]` 입니다. **행이 먼저, 열이 나중.**

- `sold[1, 2]` → 2번째 지점의 3번째 시간대
- `sold[1][2]` 도 같은 값을 주지만, 배열을 두 번 만드는 방식이라 느리고 슬라이싱과 섞이면 헷갈립니다.
  **`[행, 열]` 한 벌로 쓰는 습관**을 들이세요.

행과 열을 바꿔 쓰면 오류가 안 나고 **다른 값이 조용히 나옵니다.** 그래서 shape 확인이 중요합니다.

### 문제 14. 표에서 직사각형 잘라내기

같은 `sold` 표에서 다음 직사각형을 잘라 출력하세요.

- 행: 홍대, 판교
- 열: 점심, 저녁

결과와 `shape`를 함께 출력하고, 결과가 왜 `(2, 2)`인지 설명하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 홍대(1)부터 판교(2)까지 -> 행 슬라이스는 1:3
2. 점심(1)부터 저녁(2)까지 -> 열 슬라이스는 1:3
3. sold[1:3, 1:3]
```

In [ ]:
import numpy as np

sold = np.array([
    [42,  88, 61, 25],
    [30,  75, 94, 48],
    [55, 102, 47, 12],
])

# [옮기기] 행도 슬라이싱, 열도 슬라이싱 -> 직사각형이 나온다
rectangle = sold[1:3, 1:3]

print("홍대·판교 × 점심·저녁:\n", rectangle)
print("shape:", rectangle.shape)

홍대·판교 × 점심·저녁:
 [[ 75  94]
 [102  47]]
shape: (2, 2)


In [ ]:
assert rectangle.tolist() == [[75, 94], [102, 47]]
assert rectangle.shape == (2, 2)
print("검증 통과: 직사각형이 정확히 잘렸습니다.")

검증 통과: 직사각형이 정확히 잘렸습니다.


**해설**

행과 열 **양쪽 모두 슬라이싱**하면 결과는 직사각형(2차원)이 됩니다.

- 행 `1:3` → 홍대, 판교 (2개, stop인 3은 제외)
- 열 `1:3` → 점심, 저녁 (2개)
- 그래서 shape는 `(2, 2)`

`stop`이 제외되므로 "판교까지"를 원하면 stop에 판교의 인덱스 2가 아니라 **3**을 씁니다.

### 문제 15. 행 전체, 열 전체 선택하기

같은 `sold` 표에서 다음을 출력하세요.

1. 강남 지점의 모든 시간대 판매량
2. 모든 지점의 야간 판매량
3. 모든 지점의 점심~저녁 판매량

각 결과의 `shape`도 같이 출력해서, 1차원이 되는지 2차원이 되는지 확인하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 강남 행 전체 -> sold[0, :]
2. 야간 열 전체 -> sold[:, 3]
3. 점심~저녁 두 열 -> sold[:, 1:3]
```

In [ ]:
import numpy as np

sold = np.array([
    [42,  88, 61, 25],
    [30,  75, 94, 48],
    [55, 102, 47, 12],
])

# [옮기기] 행은 강남 하나(0), 열은 전부(:)
gangnam = sold[0, :]
print("강남 전체 시간대:", gangnam, "| shape =", gangnam.shape)

# [옮기기] 행은 전부(:), 열은 야간 하나(3)
night = sold[:, 3]
print("모든 지점 야간  :", night, "| shape =", night.shape)

# [옮기기] 행은 전부(:), 열은 점심~저녁(1:3)
lunch_dinner = sold[:, 1:3]
print("모든 지점 점심~저녁:\n", lunch_dinner, "\n| shape =", lunch_dinner.shape)

강남 전체 시간대: [42 88 61 25] | shape = (4,)
모든 지점 야간  : [25 48 12] | shape = (3,)
모든 지점 점심~저녁:
 [[ 88  61]
 [ 75  94]
 [102  47]] 
| shape = (3, 2)


In [ ]:
assert sold[0, :].shape == (4,)
assert sold[:, 3].tolist() == [25, 48, 12]
assert sold[:, 1:3].shape == (3, 2)
print("검증 통과: 축이 사라지는 규칙을 확인했습니다.")

검증 통과: 축이 사라지는 규칙을 확인했습니다.


**해설**

축을 어떻게 지정했느냐에 따라 결과의 차원이 달라집니다.

| 코드 | 행 지정 | 열 지정 | 결과 |
|---|---|---|---|
| `sold[0, :]` | 숫자 하나 | 전체 | 1차원 `(4,)` |
| `sold[:, 3]` | 전체 | 숫자 하나 | 1차원 `(3,)` |
| `sold[:, 1:3]` | 전체 | 슬라이스 | 2차원 `(3, 2)` |

**숫자 하나로 고르면 그 축은 사라지고, 슬라이스로 고르면 그 축은 남습니다.**
`sold[:, 3:4]` 처럼 슬라이스로 쓰면 `(3, 1)` 2차원이 유지됩니다.

---

## Part 6. 조건에 맞는 데이터 찾기

실제 분석 질문은 위치를 알려 주지 않습니다.

1. 조건을 실행해 `True/False` 배열을 본다
2. 그 배열을 mask로 저장한다
3. `array[mask]`로 True 위치의 값만 꺼낸다

### 문제 16. 조건 배열(mask)을 만들고 값 꺼내기

월별 방문자 데이터에서 **방문자가 2,400명을 넘은 달**을 찾으려 합니다.

순서대로 진행하세요.

1. `visitors > 2400` 을 그대로 출력해서 무엇이 나오는지 본다
2. 그 결과의 `dtype`과 `shape`를 확인한다
3. mask를 사용해 해당하는 **월**과 **방문자 수**를 각각 꺼낸다
4. 꺼낸 값이 정말 모두 2,400보다 큰지 `np.all()`로 검증한다

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 조건식 visitors > 2400 을 실행해 True/False 배열을 확인한다
2. 그 결과를 mask 변수에 저장한다
3. months[mask], visitors[mask]로 값을 꺼낸다
4. np.all(선택된 값 > 2400)로 검증한다
```

In [ ]:
import numpy as np

months = np.arange(1, 13)
visitors = np.array([1820, 1650, 2010, 2240, 2380, 2510,
                     2760, 2890, 2430, 2180, 1970, 2300])

# [옮기기] 1단계: 조건식이 무엇을 돌려주는지 먼저 본다
condition = visitors > 2400
print("조건 결과:", condition)
print("조건 dtype:", condition.dtype)
print("원본과 shape가 같은가?", visitors.shape == condition.shape)

# [옮기기] 2단계: 조건 결과를 mask로 저장한다
mask = visitors > 2400

# [옮기기] 3단계: mask를 대괄호 안에 넣어 True 위치의 값만 꺼낸다
busy_months = months[mask]
busy_visitors = visitors[mask]

print("2,400명 초과한 달 :", busy_months)
print("그 달의 방문자    :", busy_visitors)

# [옮기기] 4단계: 꺼낸 값이 모두 조건을 만족하는지 확인한다
print("모두 조건을 만족하는가?", np.all(busy_visitors > 2400))

조건 결과: [False False False False False  True  True  True  True False False False]
조건 dtype: bool
원본과 shape가 같은가? True
2,400명 초과한 달 : [6 7 8 9]
그 달의 방문자    : [2510 2760 2890 2430]
모두 조건을 만족하는가? True


In [ ]:
assert busy_months.tolist() == [6, 7, 8, 9]
assert busy_visitors.tolist() == [2510, 2760, 2890, 2430]
print("검증 통과: 조건에 맞는 달을 정확히 골랐습니다.")

검증 통과: 조건에 맞는 달을 정확히 골랐습니다.


**해설**

Boolean mask는 반드시 **두 단계**입니다.

1. `visitors > 2400` → 값이 아니라 `True/False`가 원본과 **같은 개수**로 나옵니다
2. `visitors[mask]` → True인 위치의 값만 골라 새 배열을 만듭니다

이 구조 덕분에 `months[mask]`처럼 **다른 배열에 같은 mask를 적용**할 수 있습니다.
"조건은 방문자로 걸고, 꺼내는 것은 월"이 가능한 이유입니다.
단, 두 배열의 길이가 같아야 합니다.

### 문제 17. 조건 두 개를 묶기 (& 와 |)

같은 데이터에서 다음 두 가지를 구하세요.

1. 방문자가 **2,000명 이상 2,500명 이하**인 달의 방문자 수
2. 방문자가 **1,900명 미만이거나 2,800명 초과**인 달의 방문자 수

주의: 파이썬의 `and` / `or` 가 아니라 NumPy 전용 기호를 씁니다.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 두 조건을 모두 만족 -> & 로 묶는다
2. 둘 중 하나라도 만족 -> | 로 묶는다
3. 각 조건은 반드시 소괄호로 감싼다
```

In [ ]:
import numpy as np

visitors = np.array([1820, 1650, 2010, 2240, 2380, 2510,
                     2760, 2890, 2430, 2180, 1970, 2300])

# [옮기기] 두 조건을 모두 만족 -> & (각 조건은 소괄호로 감싼다)
stable = visitors[(visitors >= 2000) & (visitors <= 2500)]

# [옮기기] 둘 중 하나라도 만족 -> |
extreme = visitors[(visitors < 1900) | (visitors > 2800)]

print("2,000 이상 2,500 이하:", stable)
print("1,900 미만 또는 2,800 초과:", extreme)
print("각각 개수:", stable.size, extreme.size)

2,000 이상 2,500 이하: [2010 2240 2380 2430 2180 2300]
1,900 미만 또는 2,800 초과: [1820 1650 2890]
각각 개수: 6 3


In [ ]:
assert stable.tolist() == [2010, 2240, 2380, 2430, 2180, 2300]
assert extreme.tolist() == [1820, 1650, 2890]
print("검증 통과: 조건 결합이 정확합니다.")

검증 통과: 조건 결합이 정확합니다.


**해설**

| 뜻 | 파이썬 기본 | NumPy 배열 |
|---|---|---|
| 그리고 | `and` | `&` |
| 또는 | `or` | `\|` |
| 아니다 | `not` | `~` |

`and` / `or`는 값 하나에 대한 참·거짓만 판단할 수 있어서, 값이 여러 개인 배열에 쓰면 오류가 납니다.

**소괄호는 생략할 수 없습니다.** `&`는 `>=` 보다 먼저 계산되기 때문에
`visitors >= 2000 & visitors <= 2500` 은 전혀 다른 뜻이 되어 버립니다.

### 문제 18. 조건에 맞는 값이 하나도 없을 때

방문자가 **5,000명을 넘은 달**을 찾아보세요. 실제로는 그런 달이 없습니다.

오류가 날까요, 아니면 다른 결과가 나올까요? **먼저 예측한 뒤** 실행하세요.

결과의 값, `shape`, `size`를 출력하고, `size`로 '결과가 비었는지'를 판단하는 코드도 작성하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. visitors > 5000 조건으로 값을 꺼낸다
2. 결과의 shape와 size를 출력한다
3. size가 0이면 '해당 없음'을 출력하는 if문을 쓴다
```

In [ ]:
import numpy as np

visitors = np.array([1820, 1650, 2010, 2240, 2380, 2510,
                     2760, 2890, 2430, 2180, 1970, 2300])

# [옮기기] 조건에 맞는 값이 없어도 오류는 나지 않는다
no_match = visitors[visitors > 5000]

print("결과:", no_match)
print("shape:", no_match.shape)
print("size :", no_match.size)

# [옮기기] 비어 있는지는 size가 0인지로 판단한다
if no_match.size == 0:
    print("해당 조건을 만족하는 달이 없습니다.")
else:
    print("평균:", no_match.mean())

결과: []
shape: (0,)
size : 0
해당 조건을 만족하는 달이 없습니다.


In [ ]:
assert no_match.size == 0
assert no_match.shape == (0,)
print("검증 통과: 빈 배열의 모양을 확인했습니다.")

검증 통과: 빈 배열의 모양을 확인했습니다.


**해설**

조건에 맞는 값이 없으면 **오류가 아니라 빈 배열 `[]`** 이 나옵니다. shape는 `(0,)`입니다.

이것이 실무에서 위험한 이유는 조용하기 때문입니다.
빈 배열에 `.mean()`을 부르면 경고와 함께 `nan`이 나오고, 그 `nan`이 리포트까지 흘러갑니다.

**조건으로 값을 꺼낸 뒤에는 `size`를 확인하는 습관**을 들이세요.
`if 결과.size == 0:` 한 줄이 나중에 몇 시간을 아껴 줍니다.

---

## Part 7. 한꺼번에 계산하기

`.sum()` `.mean()` `.min()` `.max()`
배열 × 숫자는 모든 원소에, 같은 shape 배열끼리는 같은 위치끼리 계산됩니다.

### 문제 19. 합계, 평균, 최소, 최대

월별 방문자 데이터로 다음을 출력하세요.

1. 연간 총 방문자 수
2. 월평균 방문자 수 (소수점 첫째 자리까지 반올림)
3. 가장 적었던 달의 방문자 수
4. 가장 많았던 달의 방문자 수
5. **가장 많았던 달이 몇 월인지** (`argmax` 사용)

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. sum, mean, min, max를 각각 부른다
2. 평균은 np.round(값, 1)로 반올림한다
3. 가장 많았던 '위치'는 argmax로 찾고, 그 위치를 months에 넣는다
```

In [ ]:
import numpy as np

months = np.arange(1, 13)
visitors = np.array([1820, 1650, 2010, 2240, 2380, 2510,
                     2760, 2890, 2430, 2180, 1970, 2300])

# [옮기기] 기본 통계 4종
print("연간 총 방문자:", visitors.sum())
print("월평균 방문자 :", np.round(visitors.mean(), 1))
print("최소 방문자   :", visitors.min())
print("최대 방문자   :", visitors.max())

# [옮기기] '가장 큰 값'이 아니라 '가장 큰 값의 위치'를 찾는다
peak_index = visitors.argmax()
print("최대인 위치   :", peak_index)
print("최대인 달     :", months[peak_index], "월")

연간 총 방문자: 27140
월평균 방문자 : 2261.7
최소 방문자   : 1650
최대 방문자   : 2890
최대인 위치   : 7
최대인 달     : 8 월


In [ ]:
assert visitors.sum() == 27140
assert visitors.max() == 2890
assert months[visitors.argmax()] == 8
print("검증 통과: 통계값과 최대 위치가 맞습니다.")

검증 통과: 통계값과 최대 위치가 맞습니다.


**해설**

- `max()` 는 **값**을 돌려줍니다: `2890`
- `argmax()` 는 **위치**를 돌려줍니다: `7`
- 위치를 알아야 "몇 월인지" 같은 다른 배열의 값을 함께 꺼낼 수 있습니다.

`arg` 가 붙으면 "값이 아니라 위치"라고 기억하세요. `argmin`, `argsort`도 같은 규칙입니다.

`mean()`은 실수를 돌려주므로 보고용으로는 `np.round(값, 자릿수)` 로 정리합니다.

### 문제 20. 배열끼리 계산해서 매출 구하기 (처음 질문의 답)

맨 처음 질문으로 돌아갑니다. 메뉴 5개의 가격과 판매 잔 수로 다음을 구하세요.

1. 메뉴별 매출 (가격 × 잔 수)
2. 전체 매출
3. 전체 매출에서 각 메뉴가 차지하는 비율(%) — 소수점 첫째 자리까지
4. 모든 가격을 10% 인상했을 때의 새 가격표

**한 줄로 표현되는지** 확인하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 가격 배열과 잔 수 배열을 곱하면 같은 위치끼리 곱해진다
2. 그 결과를 sum()하면 전체 매출이다
3. 비율은 (메뉴별 매출 / 전체 매출) * 100 이다
4. 10% 인상은 가격 * 1.1 이다
```

In [ ]:
import numpy as np

menu = np.array(["아메리카노", "라떼", "콜드브루", "녹차라떼", "레모네이드"])
price = np.array([4500, 5000, 5500, 5300, 6000])
cups = np.array([320, 180, 145, 60, 95])

# [옮기기] 같은 shape 배열끼리 곱하면 같은 위치끼리 곱해진다
revenue = price * cups

# [옮기기] 그 결과를 모두 더하면 전체 매출이다
total = revenue.sum()

# [옮기기] 비율 = 각 매출 / 전체 매출 * 100
share = np.round(revenue / total * 100, 1)

# [옮기기] 10% 인상 = 가격 * 1.1 (결과는 실수가 된다)
new_price = price * 1.1

print("메뉴      :", menu)
print("메뉴별 매출:", revenue)
print("전체 매출  :", total)
print("매출 비율(%):", share)
print("10% 인상가 :", new_price)
print("shape 확인 :", price.shape, cups.shape, revenue.shape)

메뉴      : ['아메리카노' '라떼' '콜드브루' '녹차라떼' '레모네이드']
메뉴별 매출: [1440000  900000  797500  318000  570000]
전체 매출  : 4025500
매출 비율(%): [35.8 22.4 19.8  7.9 14.2]
10% 인상가 : [4950. 5500. 6050. 5830. 6600.]
shape 확인 : (5,) (5,) (5,)


In [ ]:
assert revenue.tolist() == [1440000, 900000, 797500, 318000, 570000]
assert total == 4025500
print("검증 통과: 매출 계산이 정확합니다.")

검증 통과: 매출 계산이 정확합니다.


**해설**

```python
revenue = price * cups        # 반복문 없이 한 줄
total = revenue.sum()         # 합계도 한 줄
```

이것이 Part 0에서 던진 질문의 답입니다. 리스트로는 `for`문이나 `zip`이 필요했던 계산이
배열에서는 **수식 그대로** 적힙니다.

조건은 하나뿐입니다: **두 배열의 shape가 같아야 합니다.**
`price`가 5개인데 `cups`가 4개면 오류가 납니다. 그래서 계산 전에 shape를 확인합니다.

`price * 1.1` 처럼 실수를 곱하면 결과 dtype이 실수로 바뀐다는 점도 함께 보세요.

---

## Support. 더 유연하게 고르고 정렬하기

- fancy indexing: 떨어진 위치 여러 개를 한 번에 선택
- `np.sort` / `.sort()` / `argsort`
- `axis=0` 은 열마다 결과 하나, `axis=1` 은 행마다 결과 하나

### 문제 21. fancy indexing - 떨어진 위치 여러 개 고르기

`visitors`에서 **1분기의 마지막 달(3월), 2분기의 마지막 달(6월), 3분기의 마지막 달(9월)**
세 달만 골라 월과 방문자 수를 출력하세요.

슬라이싱으로는 붙어 있는 구간만 자를 수 있습니다. 떨어진 위치는 **인덱스 배열**로 고릅니다.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 3월, 6월, 9월의 인덱스는 각각 2, 5, 8이다
2. 그 위치들을 배열이나 리스트로 만든다
3. 그 배열을 대괄호 안에 넣는다
```

In [ ]:
import numpy as np

months = np.arange(1, 13)
visitors = np.array([1820, 1650, 2010, 2240, 2380, 2510,
                     2760, 2890, 2430, 2180, 1970, 2300])

# [옮기기] 3월, 6월, 9월 -> 위치는 2, 5, 8
picked = np.array([2, 5, 8])

print("선택한 위치:", picked)
print("선택한 월   :", months[picked])
print("선택한 방문자:", visitors[picked])
print("결과 shape  :", visitors[picked].shape)

선택한 위치: [2 5 8]
선택한 월   : [3 6 9]
선택한 방문자: [2010 2510 2430]
결과 shape  : (3,)


In [ ]:
assert months[picked].tolist() == [3, 6, 9]
assert visitors[picked].tolist() == [2010, 2510, 2430]
print("검증 통과: 떨어진 위치를 정확히 골랐습니다.")

검증 통과: 떨어진 위치를 정확히 골랐습니다.


**해설**

대괄호 안에 **위치 번호들의 배열**을 넣는 것을 fancy indexing이라고 합니다.

- 슬라이싱 `[2:9:3]` 은 '규칙적으로 떨어진' 경우만 가능
- fancy indexing은 `[2, 5, 8]` 처럼 **아무 순서, 아무 위치**나 가능
- 순서를 바꿔 넣으면 그 순서대로 나옵니다: `visitors[[8, 2, 5]]`
- 같은 위치를 여러 번 넣어도 됩니다

결과의 개수는 **넣은 인덱스의 개수**와 같습니다. 이 성질이 뒤의 `argsort`와 바로 연결됩니다.

### 문제 22. np.sort 와 .sort() 의 차이

바리스타 5명의 하루 제조 잔 수가 있습니다.

```python
made = np.array([182, 240, 165, 258, 203])
```

1. `np.sort(made)` 결과와, 그 뒤의 **원본** `made`를 출력하세요.
2. `made`의 사본을 만든 뒤 `.sort()`를 호출하고, **반환값**과 **사본**을 출력하세요.
3. 내림차순으로 정렬한 결과도 출력하세요.

`np.sort`와 `.sort()`가 무엇이 다른지 한 문장으로 정리하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. np.sort(made)는 새 배열을 돌려준다
2. .sort()는 그 배열 자체를 바꾸고 None을 돌려준다
3. 내림차순은 정렬한 뒤 [::-1]로 뒤집는다
```

In [ ]:
import numpy as np

made = np.array([182, 240, 165, 258, 203])

# [옮기기] 1) np.sort는 정렬된 '새 배열'을 돌려준다
sorted_made = np.sort(made)
print("np.sort 결과:", sorted_made)
print("원본 유지   :", made)

# [옮기기] 2) .sort()는 자기 자신을 바꾸고 아무것도 돌려주지 않는다
copy_made = made.copy()
returned = copy_made.sort()
print(".sort() 반환값:", returned)
print(".sort() 후 사본:", copy_made)

# [옮기기] 3) 내림차순 = 오름차순 정렬 후 뒤집기
print("내림차순:", np.sort(made)[::-1])

np.sort 결과: [165 182 203 240 258]
원본 유지   : [182 240 165 258 203]
.sort() 반환값: None
.sort() 후 사본: [165 182 203 240 258]
내림차순: [258 240 203 182 165]


In [ ]:
assert made.tolist() == [182, 240, 165, 258, 203]
assert returned is None
assert np.sort(made)[::-1].tolist() == [258, 240, 203, 182, 165]
print("검증 통과: 원본 보존 여부를 확인했습니다.")

검증 통과: 원본 보존 여부를 확인했습니다.


**해설**

| 코드 | 원본 | 반환값 |
|---|---|---|
| `np.sort(made)` | 그대로 | 정렬된 새 배열 |
| `made.sort()` | **바뀜** | `None` |

`.sort()`의 반환값이 `None`이라는 점이 중요합니다.
`made = made.sort()` 라고 쓰면 배열이 통째로 `None`이 되어 그다음 줄부터 전부 무너집니다.

NumPy에는 내림차순 옵션이 없습니다. `[::-1]`로 뒤집는 것이 표준 방법입니다.

### 문제 23. argsort로 상위 3명 뽑기

바리스타 이름과 제조 잔 수가 짝을 이루고 있습니다.

```python
baristas = np.array(["민준", "서연", "도윤", "하윤", "지호"])
made = np.array([182, 240, 165, 258, 203])
```

제조 잔 수가 **많은 순서로 상위 3명의 이름과 잔 수**를 출력하세요.

`np.sort`로는 이름을 함께 옮길 수 없습니다. **위치를 먼저 정렬**해야 합니다.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. argsort로 오름차순 '위치'를 얻는다
2. [::-1]로 뒤집어 내림차순 위치로 만든다
3. 앞 3개만 잘라 이름 배열과 잔 수 배열에 각각 넣는다
```

In [ ]:
import numpy as np

baristas = np.array(["민준", "서연", "도윤", "하윤", "지호"])
made = np.array([182, 240, 165, 258, 203])

# [옮기기] argsort는 '정렬된 값'이 아니라 '정렬 순서대로의 위치'를 준다
order_asc = np.argsort(made)
print("오름차순 위치:", order_asc)
print("확인 - 그 위치의 값:", made[order_asc])

# [옮기기] 뒤집어서 내림차순 위치로 만들고, 앞 3개만 자른다
top3 = np.argsort(made)[::-1][:3]

print("상위 3명 위치:", top3)
print("상위 3명 이름:", baristas[top3])
print("상위 3명 잔 수:", made[top3])

오름차순 위치: [2 0 4 1 3]
확인 - 그 위치의 값: [165 182 203 240 258]
상위 3명 위치: [3 1 4]
상위 3명 이름: ['하윤' '서연' '지호']
상위 3명 잔 수: [258 240 203]


In [ ]:
assert baristas[top3].tolist() == ["하윤", "서연", "지호"]
assert made[top3].tolist() == [258, 240, 203]
print("검증 통과: 상위 3명이 정확합니다.")

검증 통과: 상위 3명이 정확합니다.


**해설**

`argsort`가 돌려주는 것은 **값이 아니라 위치**입니다.

```text
made        : [182, 240, 165, 258, 203]
위치         :   0    1    2    3    4
argsort 결과 : [2, 0, 4, 1, 3]   <- 가장 작은 값(165)이 위치 2에 있다는 뜻
```

이 위치 배열을 **이름 배열에도 똑같이 적용**할 수 있기 때문에
"점수 순으로 이름 정렬"이 가능해집니다. 이것이 fancy indexing과 argsort를 함께 배우는 이유입니다.

`[::-1][:3]` 은 "뒤집고 앞 3개"입니다. 순서를 바꿔 `[:3][::-1]` 로 쓰면 하위 3명이 나옵니다.

### 문제 24. axis로 방향 정하기

지점 × 시간대 표에서 다음 두 가지를 구하세요.

1. **시간대별 합계** (아침 전체, 점심 전체, 저녁 전체, 야간 전체)
2. **지점별 합계** (강남 전체, 홍대 전체, 판교 전체)

각각 `axis=0`인지 `axis=1`인지 먼저 결정하세요.
판단 기준은 암기가 아니라 **결과가 몇 개 나와야 하는가**입니다.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 시간대는 4개이므로 결과가 4개 나와야 한다 -> 열마다 하나 -> axis=0
2. 지점은 3개이므로 결과가 3개 나와야 한다 -> 행마다 하나 -> axis=1
3. 평균도 같은 방식으로 구한다
```

In [ ]:
import numpy as np

branches = np.array(["강남", "홍대", "판교"])
timeslots = np.array(["아침", "점심", "저녁", "야간"])
sold = np.array([
    [42,  88, 61, 25],
    [30,  75, 94, 48],
    [55, 102, 47, 12],
])

print("표:\n", sold, "\nshape:", sold.shape)

# [옮기기] 시간대별 합계 -> 결과 4개 -> 열마다 하나 -> axis=0
by_timeslot = sold.sum(axis=0)
print("시간대:", timeslots)
print("시간대별 합계(axis=0):", by_timeslot, "| 개수:", by_timeslot.size)

# [옮기기] 지점별 합계 -> 결과 3개 -> 행마다 하나 -> axis=1
by_branch = sold.sum(axis=1)
print("지점  :", branches)
print("지점별 합계(axis=1):", by_branch, "| 개수:", by_branch.size)

# [옮기기] axis를 주지 않으면 전체 하나로 합쳐진다
print("전체 합계(axis 없음):", sold.sum())

표:
 [[ 42  88  61  25]
 [ 30  75  94  48]
 [ 55 102  47  12]] 
shape: (3, 4)
시간대: ['아침' '점심' '저녁' '야간']
시간대별 합계(axis=0): [127 265 202  85] | 개수: 4
지점  : ['강남' '홍대' '판교']
지점별 합계(axis=1): [216 247 216] | 개수: 3
전체 합계(axis 없음): 679


In [ ]:
assert by_timeslot.tolist() == [127, 265, 202, 85]
assert by_branch.tolist() == [216, 247, 216]
assert sold.sum() == 679
print("검증 통과: axis 방향이 정확합니다.")

검증 통과: axis 방향이 정확합니다.


**해설**

`axis`는 **"어느 축을 따라 내려가며 계산할까"**를 정합니다. 그리고 그 축은 결과에서 사라집니다.

```text
sold.shape = (3, 4)   # (행=지점 3, 열=시간대 4)

axis=0  ->  0번 축(행)이 사라짐  ->  결과 shape (4,)   = 시간대마다 하나
axis=1  ->  1번 축(열)이 사라짐  ->  결과 shape (3,)   = 지점마다 하나
```

외우지 말고 이렇게 판단하세요.
**"내가 원하는 답이 몇 개인가?"** → 4개면 `axis=0`, 3개면 `axis=1`.
`sum` 뿐 아니라 `mean`, `max`, `sort` 모두 같은 규칙입니다.

---

## Preview. AI로 이어지는 shape의 역할

암기 구간이 아닙니다. **계산 전에 shape를 확인하는 이유**만 가져갑니다.

### 문제 25. broadcasting - 다른 shape끼리 계산될 때와 안 될 때

`sold` 표(3행 4열)에 보너스 잔 수를 더하려고 합니다.

1. **시간대마다** 다른 보너스 `[1, 2, 3, 4]`를 더해 보세요. 될까요?
2. **지점마다** 다른 보너스 `[10, 20, 30]`을 그냥 더해 보세요. `try/except`로 감싸고 오류를 확인하세요.
3. 2번을 성공하도록 고치세요. (힌트: `reshape(3, 1)`)

각 단계에서 **shape를 먼저 출력**하고 예측한 뒤 실행하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 시간대 보너스는 (4,)이고 표는 (3, 4)이므로 마지막 축이 맞는다 -> 성공 예상
2. 지점 보너스는 (3,)이고 표의 마지막 축은 4이므로 어긋난다 -> 실패 예상
3. (3,)을 (3, 1)로 바꾸면 행 방향으로 펼쳐진다 -> 성공
```

In [ ]:
import numpy as np

sold = np.array([
    [42,  88, 61, 25],
    [30,  75, 94, 48],
    [55, 102, 47, 12],
])

# [옮기기] 1) 시간대별 보너스: (3,4)와 (4,) -> 마지막 축이 4로 일치하므로 성공
time_bonus = np.array([1, 2, 3, 4])
print("sold shape      :", sold.shape)
print("time_bonus shape:", time_bonus.shape)
print("시간대 보너스 적용:\n", sold + time_bonus)

# [옮기기] 2) 지점별 보너스: (3,4)와 (3,) -> 마지막 축이 4 vs 3 -> 실패
branch_bonus = np.array([10, 20, 30])
try:
    sold + branch_bonus
except ValueError as error:
    print("예상한 오류 종류:", type(error).__name__)
    print("sold shape        :", sold.shape)
    print("branch_bonus shape:", branch_bonus.shape)

# [옮기기] 3) (3,)을 (3,1)로 세워 주면 행 방향으로 펼쳐진다
column_bonus = branch_bonus.reshape(3, 1)
print("고친 shape:", column_bonus.shape)
print("지점 보너스 적용:\n", sold + column_bonus)

sold shape      : (3, 4)
time_bonus shape: (4,)
시간대 보너스 적용:
 [[ 43  90  64  29]
 [ 31  77  97  52]
 [ 56 104  50  16]]
예상한 오류 종류: ValueError
sold shape        : (3, 4)
branch_bonus shape: (3,)
고친 shape: (3, 1)
지점 보너스 적용:
 [[ 52  98  71  35]
 [ 50  95 114  68]
 [ 85 132  77  42]]


In [ ]:
assert (sold + time_bonus)[0].tolist() == [43, 90, 64, 29]
assert (sold + branch_bonus.reshape(3, 1))[2].tolist() == [85, 132, 77, 42]
print("검증 통과: broadcasting 방향을 확인했습니다.")

검증 통과: broadcasting 방향을 확인했습니다.


**해설**

Broadcasting은 shape를 **오른쪽 끝부터** 맞춰 봅니다. 각 자리가 **같거나, 한쪽이 1**이면 통과합니다.

```text
성공:  (3, 4)      실패:  (3, 4)      고침:  (3, 4)
       (   4)  ->         (   3)  ->         (3, 1)
       ------             ------             ------
       (3, 4)             4 != 3 X           (3, 4)
```

- `(4,)` 는 **모든 행에 같은 값**을 더할 때 쓰입니다 → 열(시간대)마다 다른 보너스
- `(3, 1)` 은 **모든 열에 같은 값**을 더할 때 쓰입니다 → 행(지점)마다 다른 보너스

값의 개수가 같아도(3개) **방향이 다르면 계산되지 않습니다.**
딥러닝에서 shape 오류의 절반은 이 규칙 하나로 설명됩니다.

### 문제 26. 내적과 행렬 곱으로 매출·원가를 한 번에

두 단계로 진행합니다.

**(1) 벡터 내적**
메뉴 3개의 가격 `[4500, 5000, 5500]`과 판매 잔 수 `[10, 8, 6]`이 있습니다.
`*` 결과와 `np.dot()` 결과를 각각 출력하고, 무엇이 다른지 확인하세요.

**(2) 행렬 곱**
지점 2곳 × 메뉴 3개의 판매량 표와, 메뉴 3개 × [판매가, 원가] 표를 곱하세요.
결과가 무엇을 의미하는지 해석하고, 마지막으로 `A.T`(전치)로 행과 열이 바뀌는 것도 확인하세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. * 는 원소별 곱이라 결과가 3개, np.dot은 그것을 더해 1개가 된다
2. (2,3)과 (3,2)를 곱하면 결과는 (2,2)이다
3. 결과의 [i, j]는 i지점의 j번째 항목(매출 또는 원가) 합계다
```

In [ ]:
import numpy as np

price_vec = np.array([4500, 5000, 5500])
cups_vec = np.array([10, 8, 6])

sales_count = np.array([
    [10, 8, 6],   # 강남: 아메리카노, 라떼, 콜드브루
    [12, 5, 9],   # 홍대
])
price_cost = np.array([
    [4500, 1200],   # 아메리카노: 판매가, 원가
    [5000, 1500],   # 라떼
    [5500, 1800],   # 콜드브루
])

# [옮기기] (1) * 는 같은 위치끼리 곱한 결과 여러 개
elementwise = price_vec * cups_vec
print("원소별 곱:", elementwise, "| 개수:", elementwise.size)

# [옮기기] np.dot 은 그 곱들을 모두 더한 결과 하나 -> 총매출
dot_value = np.dot(price_vec, cups_vec)
print("곱의 합  :", elementwise.sum())
print("내적     :", dot_value, "| 개수: 1")

# [옮기기] (2) (2,3) x (3,2) -> 안쪽 3이 서로 맞으므로 계산 가능, 결과는 (2,2)
result = np.dot(sales_count, price_cost)
print("sales_count shape:", sales_count.shape)
print("price_cost  shape:", price_cost.shape)
print("결과 shape       :", result.shape)
print("지점별 [총매출, 총원가]:\n", result)

# [옮기기] 첫 칸을 손으로 검산한다
print("강남 총매출 손계산:", 10 * 4500 + 8 * 5000 + 6 * 5500)

# [옮기기] 전치: 행과 열을 맞바꾼다
print("sales_count:\n", sales_count)
print("전치 결과:\n", sales_count.T)
print("shape 변화:", sales_count.shape, "->", sales_count.T.shape)

원소별 곱: [45000 40000 33000] | 개수: 3
곱의 합  : 118000
내적     : 118000 | 개수: 1
sales_count shape: (2, 3)
price_cost  shape: (3, 2)
결과 shape       : (2, 2)
지점별 [총매출, 총원가]:
 [[118000  34800]
 [128500  38100]]
강남 총매출 손계산: 118000
sales_count:
 [[10  8  6]
 [12  5  9]]
전치 결과:
 [[10 12]
 [ 8  5]
 [ 6  9]]
shape 변화: (2, 3) -> (3, 2)


In [ ]:
assert dot_value == 118000
assert result.tolist() == [[118000, 34800], [128500, 38100]]
assert sales_count.T.shape == (3, 2)
print("검증 통과: 내적과 행렬 곱이 정확합니다.")

검증 통과: 내적과 행렬 곱이 정확합니다.


**해설**

**내적은 "곱한 뒤 더하기"입니다.**

```text
[4500, 5000, 5500] · [10, 8, 6]
= 4500×10 + 5000×8 + 5500×6
= 118000        <- 값 하나
```

`*` 는 결과가 3개, `np.dot` 은 결과가 1개. 이 차이가 전부입니다.

**행렬 곱은 그 내적을 여러 번 반복한 것**입니다.

```text
(2, 3) x (3, 2) -> (2, 2)
    ^     ^
    안쪽 3이 같아야 계산 가능
    바깥의 2와 2가 결과 shape가 된다
```

결과 `[0, 0]`은 "강남 행 × 판매가 열"의 내적, 즉 **강남의 총매출**입니다.
표 두 개를 곱하는 것만으로 지점별 매출과 원가가 한 번에 나옵니다.

`.T`(전치)는 `(2, 3)`을 `(3, 2)`로 뒤집습니다. shape가 안 맞을 때 가장 먼저 시도하는 수단입니다.

---

## Final Challenge. 신메뉴 수익 분석

지금까지 배운 것을 한 문제에 모두 넣습니다.
답을 보기 전에 결과의 **개수와 첫 값**을 먼저 예측하세요.

### 문제 27. 신메뉴 4종 수익 분석 (종합)

신메뉴 4종의 판매가, 원가, 판매량 데이터입니다.

```python
new_menu   = np.array(["말차라떼", "흑임자라떼", "딸기크림", "밤라떼"])
sell_price = np.array([6000, 6500, 7000, 5800])
cost_price = np.array([2200, 2600, 3100, 2000])
sold_count = np.array([140, 95, 210, 60])
```

다음을 모두 구하세요.

1. 메뉴별 **개당 이익** (판매가 − 원가)
2. 메뉴별 **총이익** (개당 이익 × 판매량)
3. **전체 총이익**
4. 총이익이 **300,000원 이상**인 메뉴 이름
5. 총이익이 **높은 순서**의 메뉴 이름과 금액
6. 총이익이 가장 낮은 메뉴 이름 하나

**답을 쓰기 전에 예측하세요.**
- 4번의 결과는 몇 개가 나올 것 같습니까?
- 말차라떼의 총이익은 얼마입니까? (암산으로)

마지막에 "어떤 메뉴를 먼저 관리하겠는가"를 근거 한 문장으로 적으세요.

**[한글 설계]** — 코드보다 먼저 나와야 하는 문장들

```text
1. 개당 이익 = sell_price - cost_price (같은 위치끼리 빼기)
2. 총이익 = 개당 이익 * sold_count (같은 위치끼리 곱하기)
3. 전체 총이익 = 총이익.sum()
4. 30만 이상 = mask를 만들어 new_menu[mask]
5. 높은 순서 = argsort 후 [::-1]
6. 가장 낮은 것 = argmin으로 위치를 찾아 이름을 꺼낸다
```

In [ ]:
import numpy as np

new_menu = np.array(["말차라떼", "흑임자라떼", "딸기크림", "밤라떼"])
sell_price = np.array([6000, 6500, 7000, 5800])
cost_price = np.array([2200, 2600, 3100, 2000])
sold_count = np.array([140, 95, 210, 60])

# 계산 전에 shape가 모두 같은지 확인한다
print("메뉴 수:", new_menu.size)
print("shape 일치:",
      new_menu.shape == sell_price.shape == cost_price.shape == sold_count.shape)

# [옮기기] 1) 개당 이익 = 판매가 - 원가 (같은 위치끼리 빼기)
unit_profit = sell_price - cost_price

# [옮기기] 2) 총이익 = 개당 이익 × 판매량
total_profit = unit_profit * sold_count

# [옮기기] 3) 전체 총이익 = 모두 더하기
grand_total = total_profit.sum()

# [옮기기] 4) 30만 이상 -> 조건으로 mask를 만들고 이름 배열에 적용
high_mask = total_profit >= 300000
high_menu = new_menu[high_mask]

# [옮기기] 5) 높은 순서 -> argsort로 위치를 정렬하고 뒤집는다
profit_order = np.argsort(total_profit)[::-1]

# [옮기기] 6) 가장 낮은 것 -> argmin으로 위치를 찾는다
worst_index = total_profit.argmin()

print("메뉴        :", new_menu)
print("개당 이익   :", unit_profit)
print("메뉴별 총이익:", total_profit)
print("전체 총이익 :", grand_total)
print("30만 이상   :", high_menu, "| 개수:", high_menu.size)
print("총이익 내림차순 메뉴:", new_menu[profit_order])
print("총이익 내림차순 금액:", total_profit[profit_order])
print("가장 낮은 메뉴:", new_menu[worst_index], total_profit[worst_index])

메뉴 수: 4
shape 일치: True
메뉴        : ['말차라떼' '흑임자라떼' '딸기크림' '밤라떼']
개당 이익   : [3800 3900 3900 3800]
메뉴별 총이익: [532000 370500 819000 228000]
전체 총이익 : 1949500
30만 이상   : ['말차라떼' '흑임자라떼' '딸기크림'] | 개수: 3
총이익 내림차순 메뉴: ['딸기크림' '말차라떼' '흑임자라떼' '밤라떼']
총이익 내림차순 금액: [819000 532000 370500 228000]
가장 낮은 메뉴: 밤라떼 228000
