## Part 0. 왜 NumPy가 필요한가

쇼핑몰에 상품 가격 7개와 판매량 7개가 있습니다.

- 각 상품의 매출은 `가격 × 판매량`
- 전체 매출은 상품별 매출의 합

**질문:** Python 리스트만으로 이 계산을 한 줄에 자연스럽게 표현할 수 있을까요?

지금은 답을 만들지 않습니다. 먼저 우리가 기대하는 결과의 모양을 말해 봅니다.

In [3]:
prices_list = [30000, 25000, 40000]

print("리스트 * 2 결과:", prices_list * 2)
print("결과 길이:", len(prices_list * 2))

리스트 * 2 결과: [30000, 25000, 40000, 30000, 25000, 40000]
결과 길이: 6


### 관찰 해석

- Python 리스트: 여러 종류의 값을 담고 순서대로 보관하는 범용 상자
- NumPy 배열: 같은 종류의 수치 데이터를 규칙적인 모양으로 담고 한꺼번에 계산하는 도구

리스트를 버리는 것이 아니라, **계산 목적에 맞는 도구를 고르는 것**이 핵심입니다.

In [4]:
import numpy as np

print("NumPy 버전:", np.__version__)

NumPy 버전: 2.5.2


In [5]:
numbers_list = [1, 2, 3]
numbers_array = np.array(numbers_list)

print("리스트 타입:", type(numbers_list))
print("배열 타입:", type(numbers_array))
print("리스트 + 리스트:", numbers_list + numbers_list)
print("배열 + 배열:", numbers_array + numbers_array)

리스트 타입: <class 'list'>
배열 타입: <class 'numpy.ndarray'>
리스트 + 리스트: [1, 2, 3, 1, 2, 3]
배열 + 배열: [2 4 6]


In [52]:
one_dim = np.array([10, 20, 30, 40])
two_dim = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
])

print("1차원 배열:\n", one_dim)
print("2차원 배열:\n", two_dim)

1차원 배열:
 [10 20 30 40]
2차원 배열:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [7]:
for label, array in [("one_dim", one_dim), ("two_dim", two_dim)]:
    print(label)
    print("  ndim :", array.ndim)
    print("  shape:", array.shape)
    print("  size :", array.size)

one_dim
  ndim : 1
  shape: (4,)
  size : 4
two_dim
  ndim : 2
  shape: (3, 4)
  size : 12


## Part 1. 배열은 모양과 데이터 타입을 가진다

NumPy 배열은 수치 계산을 빠르고 일관되게 하기 위해 보통 하나의 공통 `dtype`을 가집니다.

- 정수: `int...`
- 실수: `float...`
- 문자열: `<U...`처럼 환경에 따라 길이 정보 포함

정확한 비트 수보다 **정수/실수/문자열 중 무엇으로 통일되었는지**를 먼저 봅니다.

In [8]:
ints = np.array([1, 2, 3])
mixed_number = np.array([1, 2, 3.5])
mixed_text = np.array([1, 2, "3"])

print(ints, "->", ints.dtype)
print(mixed_number, "->", mixed_number.dtype)
print(mixed_text, "->", mixed_text.dtype)

[1 2 3] -> int64
[1.  2.  3.5] -> float64
['1' '2' '3'] -> <U21


In [55]:
a = 10
print(type(a))
print(float(a))
b = float(a)
print(type(b))

<class 'int'>
10.0
<class 'float'>


In [9]:
heights_float = np.array([171.9, 165.2, 180.8])
heights_int = heights_float.astype(int)

print("변환 전:", heights_float, heights_float.dtype)
print("변환 후:", heights_int, heights_int.dtype)
print("원본 유지:", heights_float)

변환 전: [171.9 165.2 180.8] float64
변환 후: [171 165 180] int64
원본 유지: [171.9 165.2 180.8]


## Part 2. NumPy가 배열을 대신 만들어 준다

- `np.arange(start, stop, step)`
- `np.zeros(shape)`
- `np.ones(shape)`

반복되는 앵커: **시작은 포함, 끝은 제외**

In [10]:
print("np.arange(5)       ->", np.arange(5))
print("np.arange(2, 8)    ->", np.arange(2, 8))
print("np.arange(2, 11, 3)->", np.arange(2, 11, 3))

np.arange(5)       -> [0 1 2 3 4]
np.arange(2, 8)    -> [2 3 4 5 6 7]
np.arange(2, 11, 3)-> [2 5 8]


In [67]:
zero_table = np.zeros((2, 3), dtype=int)
zero_table = np.zeros((2, 3), dtype=float)
one_table = np.ones((2, 3))

print("0으로 채운 2행 3열:\n", zero_table)
print("1로 채운 2행 3열:\n", one_table)
print("dtype:", zero_table.dtype, one_table.dtype)



0으로 채운 2행 3열:
 [[0. 0. 0.]
 [0. 0. 0.]]
1로 채운 2행 3열:
 [[1. 1. 1.]
 [1. 1. 1.]]
dtype: float64 float64


In [77]:
arr = np.zeros((5, 4, 3, 2, 1))

arr

# arr.ndim

array([[[[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]]],



       [[[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]]],



       [[[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          

In [75]:

arr = np.zeros((3, 4, 5, 6))

arr

arr = np.zeros((4, 5, 6))

arr

arr = np.zeros((5, 6))

arr

arr = np.zeros((6))

arr

array([0., 0., 0., 0., 0., 0.])

### 미니 실습 — 먼저 설계하고 답안은 나중에 공개

1. 4부터 16까지 3씩 증가하는 배열을 만듭니다.
2. 3행 2열의 정수 0 배열을 만듭니다.

종이에 먼저 적기:

- `start = ?`
- `stop = ?`
- `step = ?`
- `shape = (?, ?)`

In [69]:
step_array = np.arange(4, 17, 3)
zero_answer = np.zeros((3, 2), dtype=int)
zero_answer = np.zeros((3, 2), dtype=float)

print("간격 배열:", step_array)
print("0 배열:\n", zero_answer)

간격 배열: [ 4  7 10 13 16]
0 배열:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


## Part 3. 배열의 모양 바꾸기

`reshape`는 값의 순서를 유지하면서 모양을 바꿉니다.

반복 질문: **숫자가 총 몇 개인가?**

10개는 `(2, 5)`, `(5, 2)`, `(1, 10)`으로 바꿀 수 있지만 `(4, 3)`에는 들어가지 않습니다.

In [78]:
base = np.arange(10)
two_by_five = base.reshape(2, 5)
five_by_two = base.reshape(5, 2)

print("원본:", base, "shape=", base.shape)
print("2행 5열:\n", two_by_five)
print("5행 2열:\n", five_by_two)
print("size:", base.size, two_by_five.size, five_by_two.size)

원본: [0 1 2 3 4 5 6 7 8 9] shape= (10,)
2행 5열:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5행 2열:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
size: 10 10 10


In [80]:
base = np.arange(10)
two_by_five = base.reshape(2, 5)
five_by_two = base.reshape(5, 3)

print("원본:", base, "shape=", base.shape)
print("2행 5열:\n", two_by_five)
print("5행 2열:\n", five_by_two)
print("size:", base.size, two_by_five.size, five_by_two.size)

ValueError: cannot reshape array of size 10 into shape (5,3)

In [81]:
try:
    impossible = base.reshape(4, 3)
except ValueError as error:
    print("예상한 오류 종류:", type(error).__name__)
    print("이유: 값 10개를 12칸 모양에 넣을 수 없습니다.")

예상한 오류 종류: ValueError
이유: 값 10개를 12칸 모양에 넣을 수 없습니다.


### 오류 분류

- 문법 오류: 아님
- 라이브러리 설치 오류: 아님
- **모양 계약 오류: 맞음**

수정 후보:

- 값 개수 10을 유지하고 `(2, 5)` 또는 `(5, 2)` 선택
- `(4, 3)`을 꼭 원하면 값 개수를 12개로 바꿈

한 번에 하나만 바꾸고 다시 실행합니다.

In [94]:
retry = base.reshape(2, 5)
print(retry)
print("retry shape:", retry.shape, "size:", retry.size)

[[0 1 2 3 4]
 [5 6 7 8 9]]
retry shape: (2, 5) size: 10


In [95]:
auto_rows = base.reshape(-1, 5)
auto_cols = base.reshape(5, -1)

print("-1, 5 ->", auto_rows.shape)
print("5, -1 ->", auto_cols.shape)

-1, 5 -> (2, 5)
5, -1 -> (5, 2)


## Part 4. 원하는 데이터를 위치로 찾기

- 첫 번째 위치: `0`
- 세 번째 위치: `2`
- 마지막 위치: `-1`
- 뒤에서 두 번째: `-2`

인덱스는 값이 아니라 **위치 번호**입니다.

In [96]:
years = np.arange(2010, 2020)
gdp = np.array([6610, 7637, 8127, 8885, 10385,
                12565, 14403, 12398, 8282, 10672])

print("연도:", years)
print("GDP :", gdp)
print("같은 길이인가?", len(years) == len(gdp))

연도: [2010 2011 2012 2013 2014 2015 2016 2017 2018 2019]
GDP : [ 6610  7637  8127  8885 10385 12565 14403 12398  8282 10672]
같은 길이인가? True


In [18]:
print("첫 번째:", gdp[0])
print("세 번째:", gdp[2])
print("마지막:", gdp[-1])
print("2012년 GDP:", gdp[2])

첫 번째: 6610
세 번째: 8127
마지막: 10672
2012년 GDP: 8127


In [97]:
gdp

array([ 6610,  7637,  8127,  8885, 10385, 12565, 14403, 12398,  8282,
       10672])

In [19]:
gdp_edit = gdp.copy()
gdp_edit[0] = 7000

print("원본 첫 값:", gdp[0])
print("수정본 첫 값:", gdp_edit[0])

원본 첫 값: 6610
수정본 첫 값: 7000


In [20]:
print("gdp[2:6] ->", gdp[2:6])
print("gdp[:3]  ->", gdp[:3])
print("gdp[7:]  ->", gdp[7:])
print("gdp[1:8:3] ->", gdp[1:8:3])

gdp[2:6] -> [ 8127  8885 10385 12565]
gdp[:3]  -> [6610 7637 8127]
gdp[7:]  -> [12398  8282 10672]
gdp[1:8:3] -> [ 7637 10385 12398]


### 미니 실습 — 위치표를 먼저 그리기

아래 배열에서 **사람이 세는 7번째부터 9번째 값까지** 가져오세요.

```python
bitcoin = np.array([
    970, 1180, 1072, 1348, 2286, 2481,
    2875, 4703, 4339, 6468, 10234, 14156
])
```

코드보다 먼저 시작 인덱스와 stop 인덱스를 적습니다.

In [21]:
bitcoin = np.array([
    970, 1180, 1072, 1348, 2286, 2481,
    2875, 4703, 4339, 6468, 10234, 14156,
])

print("7~9번째 값:", bitcoin[6:9])

7~9번째 값: [2875 4703 4339]


## Part 5. 표에서 원하는 값 찾기

2차원 배열의 기본 문장:

```python
array[행, 열]
```

행도 0부터, 열도 0부터 셉니다. 콜론 하나 `:`는 그 축을 **전부** 선택합니다.

In [98]:
regions = np.array(["서울", "부산", "대전"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4"])
sales = np.array([
    [10, 12, 14, 16],
    [20, 18, 21, 25],
    [11, 13, 15, 17],
])

print("지역:", regions)
print("분기:", quarters)
print("매출표:\n", sales)
print("shape:", sales.shape)

지역: ['서울' '부산' '대전']
분기: ['Q1' 'Q2' 'Q3' 'Q4']
매출표:
 [[10 12 14 16]
 [20 18 21 25]
 [11 13 15 17]]
shape: (3, 4)


In [23]:
busan_q3 = sales[1, 2]
print("부산 Q3 매출:", busan_q3)

부산 Q3 매출: 21


In [24]:
print("부산·대전의 Q2~Q4:\n", sales[1:3, 1:4])
print("모든 지역의 Q2~Q3:\n", sales[:, 1:3])
print("서울의 모든 분기:", sales[0, :])

부산·대전의 Q2~Q4:
 [[18 21 25]
 [13 15 17]]
모든 지역의 Q2~Q3:
 [[12 14]
 [18 21]
 [13 15]]
서울의 모든 분기: [10 12 14 16]


In [ ]:
print("부산·대전의 Q2~Q4:\n", sales[1:3, 1:4])
print("모든 지역의 Q2~Q3:\n", sales[:, 1:3])
print("서울의 모든 분기:", sales[0, :])

In [102]:
sales[1:3, 1:4]

array([[18, 21, 25],
       [13, 15, 17]])

### 미니 실습

`sales`에서 다음 직사각형을 선택하세요.

- 행: 서울, 부산
- 열: Q2, Q3

먼저 두 줄로 설계합니다.

- 행 슬라이스: `? : ?`
- 열 슬라이스: `? : ?`

In [25]:
selected_sales = sales[0:2, 1:3]
print(selected_sales)
print("shape:", selected_sales.shape)

[[12 14]
 [18 21]]
shape: (2, 2)


## Part 6. 조건에 맞는 데이터 찾기

실제 분석 질문은 보통 위치를 알려 주지 않습니다.

- GDP가 10,000보다 큰 값
- 점수가 80 이상인 학생
- 짝수만 선택

순서:

1. 조건을 실행해 `True/False` 배열을 본다.
2. 그 배열을 mask로 저장한다.
3. `array[mask]`로 True 위치의 값만 꺼낸다.

In [108]:
over_10000 = gdp > 10000

print("GDP:", gdp)
print("조건:", over_10000)
print("조건 dtype:", over_10000.dtype)
print("같은 shape:", gdp.shape == over_10000.shape)
years

GDP: [ 6610  7637  8127  8885 10385 12565 14403 12398  8282 10672]
조건: [False False False False  True  True  True  True False  True]
조건 dtype: bool
같은 shape: True


array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019])

In [107]:
mask = gdp > 10000
mask
selected_gdp = gdp[mask]
selected_gdp = gdp[gdp > 10000]
selected_years = years[mask]

print("선택된 연도:", selected_years)
print("선택된 GDP :", selected_gdp)
print("모두 조건 만족?", np.all(selected_gdp > 10000))

선택된 연도: [2014 2015 2016 2017 2019]
선택된 GDP : [10385 12565 14403 12398 10672]
모두 조건 만족? True


In [106]:
gdp

array([ 6610,  7637,  8127,  8885, 10385, 12565, 14403, 12398,  8282,
       10672])

In [28]:
btw = (gdp >= 8000) & (gdp <= 10000)
between = gdp[(gdp >= 8000) & (gdp <= 10000)]
between = gdp[btw]
outside = gdp[(gdp < 8000) | (gdp > 12000)]

print("8,000 이상 10,000 이하:", between)
print("8,000 미만 또는 12,000 초과:", outside)

8,000 이상 10,000 이하: [8127 8885 8282]
8,000 미만 또는 12,000 초과: [ 6610  7637 12565 14403 12398]


In [ ]:
gap[btw]

### 미니 실습

1부터 100까지의 정수에서 짝수만 선택합니다.

설계 질문:

1. 1부터 100까지 만들 `arange`의 stop은?
2. 짝수는 2로 나눈 나머지가 무엇인가?
3. 조건 결과를 배열 대괄호 어디에 넣는가?

In [109]:
numbers = np.arange(1, 101)
even_mask = numbers % 2 == 0
evens = numbers[even_mask]

print("앞 10개 짝수:", evens[:10])
print("마지막 짝수:", evens[-1])
print("짝수 개수:", evens.size)

앞 10개 짝수: [ 2  4  6  8 10 12 14 16 18 20]
마지막 짝수: 100
짝수 개수: 50


In [111]:
gdp

array([ 6610,  7637,  8127,  8885, 10385, 12565, 14403, 12398,  8282,
       10672])

In [110]:
no_match = gdp[gdp > 20000]

print("결과:", no_match)
print("shape:", no_match.shape)
print("size:", no_match.size)

결과: []
shape: (0,)
size: 0


## Part 7. 한꺼번에 계산하고 처음 문제 해결하기

- 합계: `.sum()`
- 평균: `.mean()`
- 최솟값: `.min()`
- 최댓값: `.max()`
- 배열 × 숫자: 모든 원소에 같은 계산
- 같은 shape 배열끼리 계산: 같은 위치끼리 계산

In [114]:
print("합계:", gdp.sum())
print("평균:", gdp.mean())
print("최솟값:", gdp.min())
print("최댓값:", gdp.max())
gdp.__dir__()
# gdp.__dict__()

합계: 99964
평균: 9996.4
최솟값: 6610
최댓값: 14403


['__new__',
 '__repr__',
 '__str__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__iter__',
 '__buffer__',
 '__add__',
 '__radd__',
 '__sub__',
 '__rsub__',
 '__mul__',
 '__rmul__',
 '__mod__',
 '__rmod__',
 '__divmod__',
 '__rdivmod__',
 '__pow__',
 '__rpow__',
 '__neg__',
 '__pos__',
 '__abs__',
 '__bool__',
 '__invert__',
 '__lshift__',
 '__rlshift__',
 '__rshift__',
 '__rrshift__',
 '__and__',
 '__rand__',
 '__xor__',
 '__rxor__',
 '__or__',
 '__ror__',
 '__int__',
 '__float__',
 '__iadd__',
 '__isub__',
 '__imul__',
 '__imod__',
 '__ipow__',
 '__ilshift__',
 '__irshift__',
 '__iand__',
 '__ixor__',
 '__ior__',
 '__floordiv__',
 '__rfloordiv__',
 '__truediv__',
 '__rtruediv__',
 '__ifloordiv__',
 '__itruediv__',
 '__index__',
 '__matmul__',
 '__rmatmul__',
 '__imatmul__',
 '__len__',
 '__getitem__',
 '__setitem__',
 '__delitem__',
 '__contains__',
 '__array__',
 '__array_finalize__',
 '__array_wrap__',
 '__array_ufunc__',
 '__array_function__',
 '__sizeof__'

In [121]:
gdp_won = gdp * 1200

print("변환 결과 앞 3개:", gdp_won[:3])
print("원본 앞 3개:", gdp[:3])
print("원본 dtype:", gdp.dtype)

변환 결과 앞 3개: [7932000 9164400 9752400]
원본 앞 3개: [6610 7637 8127]
원본 dtype: int64


In [122]:
products = np.array(["A", "B", "C", "D", "E", "F", "G"])
prices = np.array([30000, 25000, 40000, 60000, 95000, 35000, 50000])
quantities = np.array([10, 13, 7, 20, 6, 19, 9])

item_revenue = prices * quantities
total_revenue = item_revenue.sum()

print("상품:", products)
print("상품별 매출:", item_revenue)
print("전체 매출:", total_revenue)

상품: ['A' 'B' 'C' 'D' 'E' 'F' 'G']
상품별 매출: [ 300000  325000  280000 1200000  570000  665000  450000]
전체 매출: 3790000


### Core 회수

> NumPy 배열은 같은 위치와 같은 모양의 수치 데이터를 한꺼번에 질문하고 계산하게 해 준다.

지금 설명할 수 있어야 하는 것:

1. `shape`와 `size`의 차이
2. 시작 포함·끝 제외
3. `reshape`가 실패하는 이유
4. Boolean mask의 두 단계
5. 배열 연산이 같은 위치끼리 적용되는 조건

In [125]:
gdp_korea = np.array([12257, 11561, 13165, 14673, 16496, 19403])
gdp_us = np.array([36335, 37133, 38023, 39496, 41713, 44115])

gap = gdp_us - gdp_korea
ratio = gdp_us / gdp_korea

print("차이:", gap)
print("비율(소수 둘째 자리):", np.round(ratio, 2))
print("shape 일치:", gdp_korea.shape == gdp_us.shape)

차이: [24078 25572 24858 24823 25217 24712]
비율(소수 둘째 자리): [2.96 3.21 2.89 2.69 2.53 2.27]
shape 일치: True


## Support. 필요한 데이터를 더 유연하게 고르고 정렬하기

이 구간은 Core를 이해한 뒤 진행합니다.

- fancy indexing: 떨어진 위치 여러 개 선택
- sort: 값 정렬
- argsort: 정렬된 값이 아니라 원래 위치 순서 반환
- axis: 어느 축을 따라 계산할지 지정

In [127]:
chosen_indices = np.array([0, 2, 4])


print("선택 인덱스:", chosen_indices)
print("선택 연도:", years[chosen_indices])
print("선택 GDP:", gdp[chosen_indices])

선택 인덱스: [0 2 4]
선택 연도: [2010 2012 2014]
선택 GDP: [ 6610  8127 10385]


In [128]:
scores = np.array([78, 95, 84, 98, 88])
sorted_scores = np.sort(scores)

print("정렬 결과:", sorted_scores)
print("원본 유지:", scores)

정렬 결과: [78 84 88 95 98]
원본 유지: [78 95 84 98 88]


In [37]:
scores_inplace = scores.copy()
returned = scores_inplace.sort()

print("sort 반환값:", returned)
print("변경된 배열:", scores_inplace)
print("원본 scores:", scores)

sort 반환값: None
변경된 배열: [78 84 88 95 98]
원본 scores: [78 95 84 98 88]


In [38]:
descending_scores = np.sort(scores)[::-1]
print("내림차순:", descending_scores)

내림차순: [98 95 88 84 78]


### axis 앵커

2차원 표에서:

- `axis=0`: 행 방향으로 내려가며 계산 → **열마다 결과 하나**
- `axis=1`: 열 방향으로 옆으로 가며 계산 → **행마다 결과 하나**

암기 대신 결과 개수로 확인합니다.

In [130]:
axis_demo = np.array([
    [8, 12],
    [7, 1],
    [9, 5],
])

print("원본:\n", axis_demo)
print("axis=0 정렬(열마다):\n", np.sort(axis_demo, axis=0))
print("axis=1 정렬(행마다):\n", np.sort(axis_demo, axis=1))
print("axis=0 합계(열마다):", axis_demo.sum(axis=0))
print("axis=1 합계(행마다):", axis_demo.sum(axis=1))

원본:
 [[ 8 12]
 [ 7  1]
 [ 9  5]]
axis=0 정렬(열마다):
 [[ 7  1]
 [ 8  5]
 [ 9 12]]
axis=1 정렬(행마다):
 [[ 8 12]
 [ 1  7]
 [ 5  9]]
axis=0 합계(열마다): [24 18]
axis=1 합계(행마다): [20  8 14]


In [134]:
names = np.array(["John", "Mike", "Sarah", "Kate", "Samuel"])
scores = np.array([78, 95, 84, 98, 88])

order = np.argsort(scores)

print("오름차순 위치:", order)
print("오름차순 점수:", scores[order])
print("오름차순 이름:", names[order])

오름차순 위치: [0 2 4 1 3]
오름차순 점수: [78 84 88 95 98]
오름차순 이름: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 미니 실습

`names`와 `scores`를 사용해 점수 상위 3명의 이름과 점수를 높은 순서로 출력하세요.

힌트는 두 단계뿐입니다.

1. argsort 결과를 뒤집는다.
2. 앞 3개 인덱스만 사용한다.

In [41]:
top3_order = np.argsort(scores)[::-1][:3]

print("상위 3명:", names[top3_order])
print("상위 3점수:", scores[top3_order])

상위 3명: ['Kate' 'Mike' 'Samuel']
상위 3점수: [98 95 88]


## Preview. AI로 이어지는 shape의 역할

이 구간은 맛보기입니다.

- broadcasting: 서로 다른 shape를 규칙에 따라 맞춰 원소별 계산
- dot product: 곱한 뒤 더하는 계산
- matrix multiplication: 행 하나와 열 하나를 짝지어 결과 칸 생성
- transpose: 행과 열을 맞바꾸기

목표는 공식을 외우는 것이 아니라 **계산 전에 shape를 확인하는 이유**를 보는 것입니다.

In [42]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
])
bonus = np.array([1, 2, 3])

print("matrix shape:", matrix.shape)
print("bonus shape :", bonus.shape)
print("결과:\n", matrix + bonus)

matrix shape: (2, 3)
bonus shape : (3,)
결과:
 [[11 22 33]
 [41 52 63]]


In [43]:
wrong_bonus = np.array([1, 2])

try:
    matrix + wrong_bonus
except ValueError as error:
    print("예상한 오류 종류:", type(error).__name__)
    print("matrix shape:", matrix.shape)
    print("wrong_bonus shape:", wrong_bonus.shape)

예상한 오류 종류: ValueError
matrix shape: (2, 3)
wrong_bonus shape: (2,)


In [44]:
fixed_bonus = np.array([1, 2, 3])
fixed_result = matrix + fixed_bonus

print("fixed shape:", fixed_bonus.shape)
print(fixed_result)

fixed shape: (3,)
[[11 22 33]
 [41 52 63]]


### 벡터 내적 한 문장

같은 위치끼리 곱한 뒤, 그 결과를 모두 더합니다.

```text
[1, 2, 3] · [4, 5, 6]
= 1×4 + 2×5 + 3×6
= 32
```

`*`는 원소별 곱셈 결과 여러 개, `np.dot()`은 그 곱들을 더한 결과 하나를 냅니다.

In [45]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

elementwise = vector_a * vector_b
dot_value = np.dot(vector_a, vector_b)

print("원소별 곱:", elementwise)
print("곱의 합:", elementwise.sum())
print("내적:", dot_value)

원소별 곱: [ 4 10 18]
곱의 합: 32
내적: 32


In [46]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12],
])

result = np.dot(A, B)

print("A shape:", A.shape)
print("B shape:", B.shape)
print("결과 shape:", result.shape)
print("행렬 내적:\n", result)
print("첫 칸 확인:", 1*7 + 2*9 + 3*11)

A shape: (2, 3)
B shape: (3, 2)
결과 shape: (2, 2)
행렬 내적:
 [[ 58  64]
 [139 154]]
첫 칸 확인: 58


In [47]:
print("A:\n", A)
print("A.T:\n", A.T)
print("shape 변화:", A.shape, "->", A.T.shape)

A:
 [[1 2 3]
 [4 5 6]]
A.T:
 [[1 4]
 [2 5]
 [3 6]]
shape 변화: (2, 3) -> (3, 2)


In [48]:
cube = np.arange(8).reshape(2, 2, 2)

print(cube)
print("ndim:", cube.ndim)
print("shape:", cube.shape)
print("size:", cube.size)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
ndim: 3
shape: (2, 2, 2)
size: 8


## Final Challenge — 답안을 보기 전에 설계

네 상품의 가격과 판매량으로 다음을 구합니다.

1. 상품별 매출
2. 전체 매출
3. 매출이 400,000 이상인 상품 이름
4. 매출이 높은 순서의 상품 이름

진행 순서:

- Prediction: 결과 개수와 첫 상품 매출 예측
- Build: 계산식 제안
- Evidence: 출력과 검증식 실행
- Interpretation: 어떤 상품을 우선 관리할지 근거 한 문장

In [49]:
final_products = np.array(["노트", "펜", "가방", "텀블러"])
final_prices = np.array([3000, 1500, 50000, 20000])
final_quantities = np.array([120, 200, 15, 30])

print("상품 수:", final_products.size)
print("shape 일치:",
      final_products.shape == final_prices.shape == final_quantities.shape)

상품 수: 4
shape 일치: True


In [50]:
final_revenue = final_prices * final_quantities
final_total = final_revenue.sum()
high_mask = final_revenue >= 400000
revenue_order = np.argsort(final_revenue)[::-1]

print("상품별 매출:", final_revenue)
print("전체 매출:", final_total)
print("40만 이상 상품:", final_products[high_mask])
print("매출 내림차순 상품:", final_products[revenue_order])

상품별 매출: [360000 300000 750000 600000]
전체 매출: 2010000
40만 이상 상품: ['가방' '텀블러']
매출 내림차순 상품: ['가방' '텀블러' '노트' '펜']


In [51]:
assert final_revenue.tolist() == [360000, 300000, 750000, 600000]
assert final_total == 2010000
assert final_products[high_mask].tolist() == ["가방", "텀블러"]
assert final_products[revenue_order].tolist() == ["가방", "텀블러", "노트", "펜"]

print("모든 최종 검증을 통과했습니다.")

모든 최종 검증을 통과했습니다.


# 마무리

**Core**

- 배열 생성, `ndim`·`shape`·`size`·`dtype`
- `arange`, `zeros`, `ones`, `reshape`
- 1차원·2차원 indexing/slicing
- Boolean mask
- 원소별 계산과 기본 통계

**Support**

- fancy indexing, sort, argsort, axis

**Preview**

- broadcasting, dot product, matrix multiplication, transpose, 3D shape

다음 연결:

> Pandas에서는 NumPy 배열의 위치와 shape 위에 행·열 이름을 붙여 표 데이터를 더 편리하게 다룹니다.